### ISSUE TITLE
Lithium 0.5.2 for Minecraft 1.16.2 cannot run in openj9

### ISSUE THREAD

**Issue by BelowZeroKelvin** [jellysquid3/Lithium#111]
Lithium 0.5.2 for Minecraft 1.16.2 cannot run in openj9, but 0.5.1 for 1.16.1 can.

Here is my console log.

```
Loaded configuration file for Lithium: 60 options available, 0 override(s) found
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:51)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:107)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:63)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
        ... 2 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
        ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
        ... 9 more
Caused by: java.lang.ExceptionInInitializerError
        at java.base/java.lang.J9VMInternals.ensureError(Unknown Source)
        at java.base/java.lang.J9VMInternals.recordInitializationFailure(Unknown Source)
        at java.base/java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method)
        at java.base/java.lang.invoke.MethodHandle.getAdditionalBsmArg(Unknown Source)
        at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(Unknown Source)
        at net.minecraft.class_5458.<clinit>(class_5458.java:50)
        at net.minecraft.class_2378.<clinit>(class_2378.java:237)
        at net.minecraft.class_2966.method_12851(class_2966.java:42)
        at net.minecraft.server.Main.main(Main.java:88)
        ... 14 more
Caused by: java.lang.NullPointerException
        at net.minecraft.class_5458.method_30562(class_5458.java:88)
        at net.minecraft.class_5468.method_30600(class_5468.java:20)
        at net.minecraft.class_5468.<clinit>(class_5468.java:13)
        ... 21 more
```

**Comment by LucilleTea** [comment]
This is a vanilla/OpenJ9 issue, unrelated to Lithium.
https://bugs.mojang.com/browse/MC-197271
https://github.com/eclipse/openj9/issues/10356

It has been fixed in OpenJ9 as of 7 days ago, so perhaps you could use a nightly build of it as a workaround?
https://github.com/eclipse/openj9/pull/10410

**Comment by BelowZeroKelvin** [comment]
Thanks, I'll try it.

**Comment by BelowZeroKelvin** [comment]
I run it with a nightly build successful.
