### ISSUE TITLE
Crash on 1.16.4 with OptiFabric

### ISSUE THREAD

**Issue by Retr086** [jellysquid3/Lithium#168]
[16:50:23] [main/INFO]: Loading for game Minecraft 1.16.4
[16:50:23] [ForkJoinPool-1-worker-5/WARN]: Non-Fabric mod JAR at "C:\Users\OlegPC\AppData\Roaming\.minecraft\mods\OptiFine_1.16.4_HD_U_G5.jar", ignoring
[16:50:24] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Found conflicting mods: lithium conflicts with {optifabric @ [*]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:194) ~[fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:739) ~[fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:210) ~[fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:200) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:128) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:191) ~[fabric-loader-0.10.8.jar:?]
	... 5 more

**Comment by Octol1ttle** [comment]
You cannot use both Lithium and OptiFabric at the same time.
