### ISSUE TITLE
Lithium (like half the fabric universe) hard codes 1.16.4 and crashes on 1.16.5

### ISSUE THREAD

**Issue by gniftygnome** [jellysquid3/Lithium#187]
### Reproduction Steps
Install Minecraft 1.16.5 and try to start the game.

### Crash Report File
I really doubt this is needed.

### Additional Information
[10:19:04] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: lithium requires {minecraft @ [1.16.2 || 1.16.3 || 1.16.4]}
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:180) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:210) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:200) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
        at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:177) ~[fabric-server-launch.jar:?]
        ... 12 more

**Comment by Kroppeb** [comment]
Yeah, lithium makes quite a lot of changes, so we first want to make sure everything still works. However I don't expect any issues so an update could be released soon.

**Comment by jellysquid3** [comment]
> I really doubt this is needed.

Yes. This is needed. It is not a reasonable expectation for players to know what internal changes Mojang has made for an update. Lithium touches a _lot_ of internal game code, and the the risk of something silently breaking (causing world corruption, broken behavior, etc) is non-zero.

**Comment by gniftygnome** [comment]
The thing I doubted was needed was a crash file.  It's obvious why it crashes.

As for why I created the ticket, Microsoft/Mojang basically implied there are significant security issues in 1.16.4 so I have been creating tickets for all the mods which are essential on our servers.  I appreciate the mod and the responses and look forward to being able to upgrade as soon as possible.  Thanks.
