### ISSUE TITLE
1.16.5 support

### ISSUE THREAD

**Issue by magicus** [jellysquid3/Lithium#199]
I assume that supporting 1.16.5 would not be a big deal, since the changes from 1.16.4 are minimal. However, fabric is blocking lithium from loading:

```
[12:51:57] [main/INFO]: Loading for game Minecraft 1.16.5
[12:51:58] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: lithium requires {minecraft @ [1.16.2 || 1.16.3 || 1.16.4]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:180) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabric-server-launch.jar:?]
...
```

I could patch the json, but an official release would be better.

**Comment by Kroppeb** [comment]
Please read the pinned issues first: #190

If you join the discord, you'll be able to find the prerelease for 1.16.5 [here](https://discord.com/channels/602796788608401408/778685768041627719/800159881691660328).

**Comment by magicus** [comment]
Sorry, I missed the pinned issues. :-( (I must say the Github UI for them is not excellent...)

I accept your judgement that there is more to an update than meets the eye.
