### ISSUE TITLE
Crashed when I broke a spider string attached to a dispenser in a jungle temple

### ISSUE THREAD

**Issue by inikishev** [jellysquid3/Lithium#215]
### Reproduction Steps
Crashed when I broke a spider string attached to a dispencer in a jungle temple.
Now it crashes when I try loading that save. (the attached log both is crashing after removing the string and then second crashing when I tried to load the save)

### Crash Report File
https://gist.githubusercontent.com/idkman2021/24a5ffe669d105accf0f2af06b3ab7df/raw/0493a9995fcab747d703c22bf5e4c4c9296bebe3/latest.log

this is the error
```
[17:43:54] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception while ticking
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.3) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:875) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91) ~[?:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
Caused by: java.lang.NullPointerException
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.3) ~[?:?]
	at net.minecraft.block.DispenserBlock.handler$zle000$interrupt(DispenserBlock:1023) ~[?:?]
	at net.minecraft.block.DispenserBlock.dispense(DispenserBlock:86) ~[?:?]
	at net.minecraft.block.DispenserBlock.scheduledTick(DispenserBlock:112) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.scheduledTick(AbstractBlock:874) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tickBlock(ServerWorld:602) ~[?:?]
	at me.jellysquid.mods.lithium.common.world.scheduler.LithiumServerTickScheduler.executeTicks(LithiumServerTickScheduler.java:228) ~[lithium-fabric-mc1.16.5-0.6.3.jar:?]
	at me.jellysquid.mods.lithium.common.world.scheduler.LithiumServerTickScheduler.tick(LithiumServerTickScheduler.java:73) ~[lithium-fabric-mc1.16.5-0.6.3.jar:?]
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:357) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:871) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	... 5 more
```

**Comment by 2No2Name** [comment]
This is very likely to not be caused by Lithium. I think the problem is a mod that modifies dispensers, or somehow tracks what dispensers do.

**Comment by DragonEggBedrockBreaking** [comment]
> 
> 
> This is very likely to not be caused by Lithium. I think the problem is a mod that modifies dispensers, or somehow tracks what dispensers do.

Confirmed your point: Cannot reproduce myself with only Lithium 0.6.3 (latest release).
