### ISSUE TITLE
Can't start server anymore.

### ISSUE THREAD

**Issue by Maelep** [jellysquid3/Lithium#229]
I'm hosting a server that use some mods. All was fine but, one hour ago, my server crashed and now, as soon as a player joins the server, it crashes again.

I don't know from where the bug comes but it contains your mod name. Perhaps the bug comes from your mods.

[Console Error](https://dpaste.com/6T8C5SMJP) and [Crash Report](https://dpaste.com/GLEHQW5D9)

Console Error:
`[20:47:07] [User Authenticator #1/INFO]: UUID of player Plaget is #UID#.
[20:47:08] [Server thread/INFO]: Plaget[/#IP#:#PORT#] logged in with entity id 314 at (22.68302787498996, 64.0, 289.3344642357117)
[20:47:08] [Server thread/INFO]: Plaget joined the game
[20:47:09] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception while ticking
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.Arrays$ArrayList.get(Arrays.java:3841) ~[?:1.8.0_282]
        at net.minecraft.class_2371.get(class_2371.java:46) ~[intermediary-server.jar:?]
        at net.minecraft.class_2621.method_5438(class_2621.java:99) ~[intermediary-server.jar:?]
        at alexiil.mc.lib.attributes.item.compat.FixedInventoryViewVanillaWrapper.getInvStack(FixedInventoryViewVanillaWrapper.java:35) ~[bff75135-da70-43b3-be79-66ae58581a67.jar:?]
        at alexiil.mc.lib.attributes.item.FixedItemInv.extractStack(FixedItemInv.java:145) ~[bff75135-da70-43b3-be79-66ae58581a67.jar:?]
        at alexiil.mc.lib.attributes.item.SingleItemSlot.attemptExtraction(SingleItemSlot.java:53) ~[bff75135-da70-43b3-be79-66ae58581a67.jar:?]
        at alexiil.mc.lib.attributes.item.ItemInvUtil.move(ItemInvUtil.java:110) ~[bff75135-da70-43b3-be79-66ae58581a67.jar:?]
        at alexiil.mc.lib.attributes.item.ItemInvUtil.move(ItemInvUtil.java:91) ~[bff75135-da70-43b3-be79-66ae58581a67.jar:?]
        at alexiil.mc.lib.attributes.item.ItemInvUtil.move(ItemInvUtil.java:82) ~[bff75135-da70-43b3-be79-66ae58581a67.jar:?]
        at alexiil.mc.lib.attributes.item.mixin.HopperHooks.tryDispense(HopperHooks.java:121) ~[bff75135-da70-43b3-be79-66ae58581a67.jar:?]
        at net.minecraft.class_2325.handler$zhl000$dispenseIntoLba(class_2325.java:1037) ~[intermediary-server.jar:?]
        at net.minecraft.class_2325.method_10012(class_2325.java:39) ~[intermediary-server.jar:?]
        at net.minecraft.class_2315.method_9588(class_2315.java:112) ~[intermediary-server.jar:?]
        at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:874) ~[intermediary-server.jar:?]
        at net.minecraft.class_3218.method_14189(class_3218.java:602) ~[intermediary-server.jar:?]
        at net.minecraft.class_1949.method_8670(class_1949.java:84) ~[intermediary-server.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:357) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[intermediary-server.jar:?]
        ... 5 more
[20:47:09] [Server thread/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2021-04-11_20.47.09-server.txt
[20:47:09] [Server thread/INFO]: Stopping server`

**Comment by jellysquid3** [comment]
Per the issue template... have you tried to reproduce this crash _without_ Lithium installed?

**Comment by Maelep** [comment]
Yes, I removed Lithium and some other plugins. It still crash.
From the crash report, I see that a block is mentioned. I'll try to remove it using MCEdit

**Comment by DragonEggBedrockBreaking** [comment]
> Yes, I removed Lithium and some other plugins. It still crash.
> From the crash report, I see that a block is mentioned. I'll try to remove it using MCEdit

If it crashes without lithium, then it is not a lithium bug.

**Comment by Maelep** [comment]
Ok but can Lithium corrupt a block so now it crashes?

**Comment by Maelep** [comment]
Fixed by manually updating LibBlockAttributes ([GitHub Issue](https://github.com/AlexIIL/LibBlockAttributes/issues/43)).
