### ISSUE TITLE
Missing gameteststructures directory causes the game to crash in dev

### ISSUE THREAD

**Issue by FakeDomi** [jellysquid3/Lithium#252]
Using the 1.17/dev branch

The game crashes when `gameteststructures` directory doesn't exist inside the run dir, and it's not there by default.
It should be added to the repo.

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mctester'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:459)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
	at mctester.annotation.TestRegistryHelper.createTemplatedTestsFromFiles(TestRegistryHelper.java:38)
	at mctester.McTesterMod.onInitialize(McTesterMod.java:30)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 12 more
```

**Comment by 2No2Name** [comment]
I consider this to be a bug in McTester (https://github.com/2No2Name/mctester). I fixed it there. I updated the dependency in https://github.com/CaffeineMC/lithium-fabric/commit/971390ae537f9931c68ea8b22cc4edc206a646cf . I think this should be fixed now
