### ISSUE TITLE
Lithium 1.15.2 crash

### ISSUE THREAD

**Issue by Jackson-eng** [jellysquid3/Lithium#264]
- I have used the search tool to find similar issues and made sure I am not opening a duplicate
- I am using the latest version of the mod

When running the compiled 1.15.x version it errors:
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 7/28/21 12:17 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access method net.minecraft.class_265.<init>(Lnet/minecraft/class_251;)V from class me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube
	at me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube.<init>(VoxelShapeSimpleCube.java:23)
	at net.minecraft.class_259.method_1078(class_259.java:552)
	at net.minecraft.class_259.method_1081(class_259.java:53)
	at net.minecraft.class_259.<clinit>(class_259.java:32)
	at net.minecraft.class_2248.<clinit>(class_2248.java:114)
	at net.minecraft.class_2246.<clinit>(class_2246.java:24)
	at net.minecraft.class_2378.method_10237(class_2378.java:81)
	at net.minecraft.class_2378$$Lambda$151/34073107.get(Unknown Source)
	at net.minecraft.class_2378.method_10238(class_2378.java:125)
	at net.minecraft.class_2378$$Lambda$189/1269118128.accept(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
	at net.minecraft.class_2378.<clinit>(class_2378.java:124)
	at net.minecraft.class_2966.method_12851(class_2966.java:38)
	at net.minecraft.class_310.<init>(class_310.java:386)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube.<init>(VoxelShapeSimpleCube.java:23)
	at net.minecraft.class_259.method_1078(class_259.java:552)
	at net.minecraft.class_259.method_1081(class_259.java:53)
	at net.minecraft.class_259.<clinit>(class_259.java:32)
	at net.minecraft.class_2248.<clinit>(class_2248.java:114)
	at net.minecraft.class_2246.<clinit>(class_2246.java:24)
	at net.minecraft.class_2378.method_10237(class_2378.java:81)
	at net.minecraft.class_2378$$Lambda$151/34073107.get(Unknown Source)
	at net.minecraft.class_2378.method_10238(class_2378.java:125)
	at net.minecraft.class_2378$$Lambda$189/1269118128.accept(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
	at net.minecraft.class_2378.<clinit>(class_2378.java:124)
	at net.minecraft.class_2966.method_12851(class_2966.java:38)
	at net.minecraft.class_310.<init>(class_310.java:386)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 91066720 bytes (86 MB) / 201326592 bytes (192 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.11.6-1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```
I also attached the compiled/built jar I was using: [lithium-mc1.15.2-fabric-0.4.6.jar.zip](https://github.com/CaffeineMC/lithium-fabric/files/6895956/lithium-mc1.15.2-fabric-0.4.6.jar.zip)

**Comment by QPCrummer** [comment]
1.15.2 is not supported anymore

**Comment by 2No2Name** [comment]
This is likely caused by certain other mods being present

**Comment by Jackson-eng** [comment]
> This is likely caused by certain other mods being present

Only other mods are other caffeine my stuff

**Comment by 2No2Name** [comment]
Without the list of mods there is nothing we can do.
