### ISSUE TITLE
[Server] Lithium incompatible with Fabric Loader 0.12.9

### ISSUE THREAD

**Issue by nathansmeal** [jellysquid3/Lithium#308]
### Version
lithium-fabric-mc1.18-0.7.6-rc1.jar
### Reproduction Steps

Update to fabric 10.2

start server with lithium installed - class errors
remove lithium - server starts normally

**Comment by DragonEggBedrockBreaking** [comment]
How are you using fabric 10.2? The latest fabric version is 0.12.9. Maybe you are confusing the fabric loader with the fabric installer?

**Comment by nathansmeal** [comment]
I am running a dedicated server, as far as I know you don't need the fabric loader for that. The most recent version of the fabric installer is 0.10.2. I could be wrong though

**Comment by jellysquid3** [comment]
Fabric Loader (the mod loader itself) is required.

Fabric API (a Fabric mod which provides some basic functionality for modders) is not required for Lithium, but is typically required for other mods.

Fabric Installer simply installs Fabric Loader into your game, whether a dedicated server or client. It's then the user's responsibility to install Fabric API and/or any of their other mods to the folder that Fabric Loader creates.

Provide a crash log if you are having issues. We are (regrettably) not psychic.

**Comment by AlligatorFarts** [comment]
```
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[09:37:44] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18 with Fabric Loader 0.12.9
[09:37:45] [main/INFO]: Loading Minecraft 1.18 with Fabric Loader 0.12.9
[09:37:45] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d95c8 recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
         - You should install any version of fabric-textures-v0 for the optimal experience.
[09:37:45] [main/INFO]: Loading 38 mods:
        - fabric 0.44.0+1.18
        - fabric-api-base 0.4.1+b4f4f6cdc8 via fabric
        - fabric-api-lookup-api-v1 1.4.0+16d92c47c8 via fabric
        - fabric-biome-api-v1 6.0.1+ded849a9c8 via fabric
        - fabric-command-api-v1 1.1.6+3ac43d95c8 via fabric
        - fabric-commands-v0 0.2.5+b4f4f6cdc8 via fabric
        - fabric-containers-v0 0.1.18+d154e2c6c8 via fabric
        - fabric-content-registries-v0 0.4.5+6f53a73dc8 via fabric
        - fabric-crash-report-info-v1 0.1.8+3ac43d95c8 via fabric
        - fabric-dimensions-v1 2.1.7+43d29571c8 via fabric
        - fabric-entity-events-v1 1.4.5+6b21378ac8 via fabric
        - fabric-events-interaction-v0 0.4.16+bfa23f17c8 via fabric
        - fabric-events-lifecycle-v0 0.2.6+b4f4f6cdc8 via fabric
        - fabric-game-rule-api-v1 1.0.10+3ac43d95c8 via fabric
        - fabric-item-api-v1 1.3.0+691a79b5c8 via fabric
        - fabric-item-groups-v0 0.3.3+3ac43d95c8 via fabric
        - fabric-lifecycle-events-v1 1.4.10+c15ca335c8 via fabric
        - fabric-loot-tables-v1 1.0.8+3ac43d95c8 via fabric
        - fabric-mining-level-api-v1 1.0.3+3ac43d95c8 via fabric
        - fabric-mining-levels-v0 0.1.7+b4f4f6cdc8 via fabric
        - fabric-networking-api-v1 1.0.18+3ac43d95c8 via fabric
        - fabric-networking-v0 0.3.5+b4f4f6cdc8 via fabric
        - fabric-object-builder-api-v1 1.11.0+3b82842ec8 via fabric
        - fabric-object-builders-v0 0.7.8+3ac43d95c8 via fabric
        - fabric-particles-v1 0.2.9+526dc1acc8 via fabric
        - fabric-registry-sync-v0 0.8.5+3ac43d95c8 via fabric
        - fabric-rendering-data-attachment-v1 0.3.4+7242e9d7c8 via fabric
        - fabric-rendering-fluids-v1 0.1.18+3ac43d95c8 via fabric
        - fabric-resource-loader-v0 0.4.11+3ac43d95c8 via fabric
        - fabric-screen-handler-api-v1 1.1.11+3ac43d95c8 via fabric
        - fabric-structure-api-v1 2.0.8+295197a7c8 via fabric
        - fabric-tag-extensions-v0 1.2.5+3ac43d95c8 via fabric
        - fabric-tool-attribute-api-v1 1.3.4+7de09f55c8 via fabric
        - fabric-transfer-api-v1 1.5.5+b4f4f6cdc8 via fabric
        - fabricloader 0.12.9
        - java 17
        - lithium 0.7.6-rc1
        - minecraft 1.18
[09:37:45] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/nate/fabric/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=SERVER
[09:37:46] [main/INFO]: Compatibility level set to JAVA_16
[09:37:46] [main/INFO]: Loaded configuration file for Lithium: 86 options available, 0 override(s) found
[09:37:48] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:604) ~[fabric-loader-0.12.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.9.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.9.jar:?]
Caused by: java.lang.ExceptionInInitializerError
        at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
        at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
        at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
        at net.minecraft.class_2939.<clinit>(class_2939.java:31) ~[server-intermediary.jar:?]
        at net.minecraft.class_5463.<clinit>(class_5463.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30572(class_5458.java:46) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:723) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:97) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) ~[fabric-loader-0.12.9.jar:?]
        ... 7 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3218 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234) ~[fabric-loader-0.12.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:103) ~[server-intermediary.jar:?]
        at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
        at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
        at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
        at net.minecraft.class_2939.<clinit>(class_2939.java:31) ~[server-intermediary.jar:?]
        at net.minecraft.class_5463.<clinit>(class_5463.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30572(class_5458.java:46) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:723) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:97) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) ~[fabric-loader-0.12.9.jar:?]
        ... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:103) ~[server-intermediary.jar:?]
        at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
        at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
        at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
        at net.minecraft.class_2939.<clinit>(class_2939.java:31) ~[server-intermediary.jar:?]
        at net.minecraft.class_5463.<clinit>(class_5463.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30572(class_5458.java:46) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:723) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:97) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) ~[fabric-loader-0.12.9.jar:?]
        ... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method startWorldTick(Ljava/util/function/BooleanSupplier;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in fabric-lifecycle-events-v1.mixins.json:ServerWorldMixin from mod fabric-lifecycle-events-v1 failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-lifecycle-events-v1-refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:103) ~[server-intermediary.jar:?]
        at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
        at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
        at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
        at net.minecraft.class_2939.<clinit>(class_2939.java:31) ~[server-intermediary.jar:?]
        at net.minecraft.class_5463.<clinit>(class_5463.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30572(class_5458.java:46) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:723) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:97) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) ~[fabric-loader-0.12.9.jar:?]
        ... 7 more

**Comment by nathansmeal** [comment]
[error.txt](https://github.com/CaffeineMC/lithium-fabric/files/7694481/error.txt)

here is my output when starting the server. it was working and all I did was update fabric loader using the 0.10.2 installer and now lithium is giving me issues

**Comment by Mangraz** [comment]
A server with 0.12.9 installed does indeed not start when Lithium is installed

**Comment by AViewFromTheTop** [comment]
Is this on 1.18.1? I've tested with 12.9 and it works fine on 1.18, just not 1.18.1.

**Comment by nathansmeal** [comment]
Its 1.18 Server running on linux, what is your configuration?

**Comment by Mangraz** [comment]
1.18.1 on Windows here. In my case the log even explicitly states there's a compatibility issue [2021-12-10-6.log](https://github.com/CaffeineMC/lithium-fabric/files/7694867/2021-12-10-6.log)

**Comment by nathansmeal** [comment]
It's actually stated somewhere in the lithium pages that they only allow specific versions of minecraft, ie if there is an update it will break lithium. However I have only updated fabric and not minecraft.

**Comment by Mangraz** [comment]
I was under the assumption that 0.12.9 was exclusive to 1.18.1, since installing a 0.12.9 server using the installer (10.2, same as you are using) installed a 1.18.1 server.

**Comment by nathansmeal** [comment]
I am running 1.18 with 12.9 just without lithium atm. I believe there is an option to download the current version of minecraft when installing fabric. That might be what happened to you?

**Comment by Mangraz** [comment]
Oh yeah, of course! I did decide to reinstall everything from scratch. Well, gonna go without Lithium and wait for it to get updated then.

**Comment by omash03** [comment]
1.18.1 fabric loader 0.12.9 does not work with lithium at the moment, this is the crash I get

[crash-2021-12-11_15.28.33-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/7698650/crash-2021-12-11_15.28.33-server.txt)

**Comment by name-here** [comment]
1.18.1 fixes a pretty serious security vulnerability, but I don't think it's a big change, so I hope Lithium gets updated soon.

**Comment by nathansmeal** [comment]
I believe the fabric 0.10.2 installer also patches this vulnerability without having to update to 1.18.1

**Comment by daniel-widrick** [comment]
> I believe the fabric 0.10.2 installer also patches this vulnerability without having to update to 1.18.1

Reverting to 1.18 is not a viable option. In our case we'll be unable to run lithium until it supports 1.18.1

**Comment by nathansmeal** [comment]
> > I believe the fabric 0.10.2 installer also patches this vulnerability without having to update to 1.18.1
> 
> Reverting to 1.18 is not a viable option. In our case we'll be unable to run lithium until it supports 1.18.1

That's understandable, but this is not the issue that this post is based on. In fact, Lithum will not automatically support newer versions of minecraft. That is intended, while this is not

**Comment by 2No2Name** [comment]
Might be related to https://github.com/CaffeineMC/lithium-fabric/issues/326

**Comment by 2No2Name** [comment]
Is this still an issue for the newer releases?

**Comment by Mangraz** [comment]
I was using a snapshot of Lithium 0.7.6 I downloaded in late December with no issues until earlier today. Updated to 0.7.7 now and no issues so far on the server. Edit: I am using Fabric 0.12.12 now, so my feedback probably isn't valuable for this issue anymore
