### ISSUE TITLE
MaskedList illegal state

### ISSUE THREAD

**Issue by Eragoneq** [jellysquid3/Lithium#356]
### Version

`lithium-fabric-mc1.18.2-0.7.9`

### Reproduction Steps

Example:
1.  Join server (Hypixel/Wynncraft in my example)
2.  Minimize/change focus/stream the window on Discord
3.  Get the crash like the one below

### Crash Report File

https://paste.ee/p/VtWrO

### Additional Information

I didn't find any other issue online mentioning the `MaskedList` and I wasn't able to really reproduce the issue in isolation. It also seems pretty random as it just sometimes happens, probably when something comes into the render distance.

**Comment by 2No2Name** [comment]
Something is putting the same entity twice into an entity section. It is unclear why this happens, maybe it is a vanilla bug or another mod doing this.

**Comment by James103** [comment]
Converted the paste to a text file as the paste has an expiry date: [Crash report.txt](https://github.com/CaffeineMC/lithium-fabric/files/8346010/Crash.report.txt)

**Comment by 2No2Name** [comment]
Something is wrong about this modded server. It seems to be sending a lot of duplicate entities (see log). However I will try to make it not crash on our side.

**Comment by Kepler-17c** [comment]
I also have this issue on Wynncraft.
If you need more crash reports or logs, I can send you what I have.

Since I know the head dev of Wynncraft, is there anything I can forward to him?

**Comment by 2No2Name** [comment]
Tell them to not send entities with duplicate entity id to the client

**Comment by Kepler-17c** [comment]
I forwarded the issue and added some details from my crash reports, but as a proxy I can't really help solve the issue.

Can you add him in Discord? HeyZeer0#0190
Would also be great if I could forward your account, so he know it's you - is it 2No2Name#1633 (found on Iris & ReplayMod)?

**Comment by 2No2Name** [comment]
Was fixed in 0.7.10

**Comment by Kepler-17c** [comment]
Excuse me, but how is it fixed in 0.7.10? I've been using this version for months and it's the one I encountered this issue on.

Here's a recent crash when I tried using it again:  
(server: Wynncraft, mod list below)

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 20/05/2022, 19:32
Description: Ticking entity

java.lang.IllegalStateException: MaskedList must not contain duplicates!
	at me.jellysquid.mods.lithium.common.util.collections.MaskedList.add(MaskedList.java:92)
	at net.minecraft.class_5572.onStartClimbingCachingEntity(class_5572.java:2604)
	at net.minecraft.class_5572.startFilteringPushableEntities(class_5572.java:2574)
	at net.minecraft.class_5572.collectPushableEntities(class_5572.java:2567)
	at me.jellysquid.mods.lithium.common.world.WorldHelper.lambda$getPushableEntities$1(WorldHelper.java:84)
	at net.minecraft.class_5573.consumeSection(class_5573.java:1581)
	at net.minecraft.class_5573.forEachInColumn(class_5573.java:1570)
	at net.minecraft.class_5573.handler$zne000$forEachInBox(class_5573.java:1562)
	at net.minecraft.class_5573.method_31777(class_5573.java:52)
	at me.jellysquid.mods.lithium.common.world.WorldHelper.getPushableEntities(WorldHelper.java:84)
	at net.minecraft.class_1309.redirect$zmo002$getOtherPushableEntities(class_1309.java:4085)
	at net.minecraft.class_1309.method_6070(class_1309.java:2726)
	at net.minecraft.class_1309.method_6007(class_1309.java:2678)
	at net.minecraft.class_1308.method_6007(class_1308.java:546)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1429.method_6007(class_1429.java:58)
	at net.minecraft.class_1496.method_6007(class_1496.java:553)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1308.method_5773(class_1308.java:346)
	at net.minecraft.class_1496.method_5773(class_1496.java:594)
	at net.minecraft.class_638.method_18646(class_638.java:217)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_638.method_32124(class_638.java:200)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:196)
	at net.minecraft.class_310.method_1574(class_310.java:1761)
	at com.replaymod.replay.ReplayHandler.doJump(ReplayHandler.java:722)
	at com.replaymod.replay.gui.overlay.GuiReplayOverlay$7.run(GuiReplayOverlay.java:131)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.advanced.AbstractGuiTimeline.onClick(AbstractGuiTimeline.java:197)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.advanced.AbstractGuiTimeline.mouseClick(AbstractGuiTimeline.java:280)
	at com.replaymod.replay.gui.overlay.GuiMarkerTimeline.mouseClick(GuiMarkerTimeline.java:188)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiOverlay$UserInputGuiScreen.lambda$mouseClicked$2(AbstractGuiOverlay.java:309)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$7(ComposedGuiElement.java:82)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:71)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$6(ComposedGuiElement.java:81)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:68)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$5(ComposedGuiElement.java:74)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.forEach(ComposedGuiElement.java:42)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:74)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiOverlay$UserInputGuiScreen.method_25402(AbstractGuiOverlay.java:309)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1147)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.lithium.common.util.collections.MaskedList.add(MaskedList.java:92)
	at net.minecraft.class_5572.onStartClimbingCachingEntity(class_5572.java:2604)
	at net.minecraft.class_5572.startFilteringPushableEntities(class_5572.java:2574)
	at net.minecraft.class_5572.collectPushableEntities(class_5572.java:2567)
	at me.jellysquid.mods.lithium.common.world.WorldHelper.lambda$getPushableEntities$1(WorldHelper.java:84)
	at net.minecraft.class_5573.consumeSection(class_5573.java:1581)
	at net.minecraft.class_5573.forEachInColumn(class_5573.java:1570)
	at net.minecraft.class_5573.handler$zne000$forEachInBox(class_5573.java:1562)
	at net.minecraft.class_5573.method_31777(class_5573.java:52)
	at me.jellysquid.mods.lithium.common.world.WorldHelper.getPushableEntities(WorldHelper.java:84)
	at net.minecraft.class_1309.redirect$zmo002$getOtherPushableEntities(class_1309.java:4085)
	at net.minecraft.class_1309.method_6070(class_1309.java:2726)
	at net.minecraft.class_1309.method_6007(class_1309.java:2678)
	at net.minecraft.class_1308.method_6007(class_1308.java:546)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1429.method_6007(class_1429.java:58)
	at net.minecraft.class_1496.method_6007(class_1496.java:553)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1308.method_5773(class_1308.java:346)
	at net.minecraft.class_1496.method_5773(class_1496.java:594)
	at net.minecraft.class_638.method_18646(class_638.java:217)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_638.method_32124(class_638.java:200)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:196)
	at net.minecraft.class_310.method_1574(class_310.java:1761)
	at com.replaymod.replay.ReplayHandler.doJump(ReplayHandler.java:722)
	at com.replaymod.replay.gui.overlay.GuiReplayOverlay$7.run(GuiReplayOverlay.java:131)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.advanced.AbstractGuiTimeline.onClick(AbstractGuiTimeline.java:197)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.advanced.AbstractGuiTimeline.mouseClick(AbstractGuiTimeline.java:280)
	at com.replaymod.replay.gui.overlay.GuiMarkerTimeline.mouseClick(GuiMarkerTimeline.java:188)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiOverlay$UserInputGuiScreen.lambda$mouseClicked$2(AbstractGuiOverlay.java:309)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$7(ComposedGuiElement.java:82)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:71)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$6(ComposedGuiElement.java:81)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:68)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$5(ComposedGuiElement.java:74)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.forEach(ComposedGuiElement.java:42)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:74)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiOverlay$UserInputGuiScreen.method_25402(AbstractGuiOverlay.java:309)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204)

-- Entity being ticked --
Details:
	Entity Type: minecraft:horse (net.minecraft.class_1498)
	Entity ID: 1639402528
	Entity Name: Horse
	Entity's Exact location: 438.80, 70.00, -1614.28
	Entity's Block location: World: (438,70,-1615), Section: (at 6,6,1 in 27,4,-101; chunk contains blocks 432,0,-1616 to 447,255,-1601), Region: (0,-4; contains chunks 0,-128 to 31,-97, blocks 0,0,-2048 to 511,255,-1537)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_638.method_32124(class_638.java:200)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:196)
	at net.minecraft.class_310.method_1574(class_310.java:1761)
	at com.replaymod.replay.ReplayHandler.doJump(ReplayHandler.java:722)
	at com.replaymod.replay.gui.overlay.GuiReplayOverlay$7.run(GuiReplayOverlay.java:131)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.advanced.AbstractGuiTimeline.onClick(AbstractGuiTimeline.java:197)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.advanced.AbstractGuiTimeline.mouseClick(AbstractGuiTimeline.java:280)
	at com.replaymod.replay.gui.overlay.GuiMarkerTimeline.mouseClick(GuiMarkerTimeline.java:188)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiOverlay$UserInputGuiScreen.lambda$mouseClicked$2(AbstractGuiOverlay.java:309)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$7(ComposedGuiElement.java:82)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:71)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$6(ComposedGuiElement.java:81)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:68)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$5(ComposedGuiElement.java:74)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.forEach(ComposedGuiElement.java:42)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:74)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiOverlay$UserInputGuiScreen.method_25402(AbstractGuiOverlay.java:309)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1147)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected screen --
Details:
	Screen name: com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiOverlay.UserInputGuiScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1147)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 220 total; [omitted players to reduce the size of this post - can post in full if needed]
	Chunk stats: 65536, 169 F: 14547 L: 0 U: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (-1571,41,-1668), Section: (at 13,9,12 in -99,2,-105; chunk contains blocks -1584,0,-1680 to -1569,255,-1665), Region: (-4,-4; contains chunks -128,-128 to -97,-97, blocks -2048,0,-2048 to -1537,255,-1537)
	Level time: 4865915158 game time, 388633460 day time
	Server brand: Wynncraft <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, replaymod_lang

-- Wynntils --
Details:
	In Development: Yes
	Loaded Features: 
		feature.wynntils.com.wynntils.features.SoulPointTimer.name
		featureDebug.wynntils.com.wynntils.features.debug.PacketDebugger.name
		feature.wynntils.com.wynntils.features.ItemStatInfo.name
		feature.wynntils.com.wynntils.features.PlayerGhostTransparency.name
		feature.wynntils.com.wynntils.features.IngredientPouchHotkey.name
		feature.wynntils.com.wynntils.features.WynncraftButton.name
		feature.wynntils.com.wynntils.features.ItemScreenshot.name
		feature.wynntils.com.wynntils.features.ItemGuess.name
		feature.wynntils.com.wynntils.features.DialogueOptionOverride.name
		featureDebug.wynntils.com.wynntils.features.debug.KeyBindTest.name
		feature.wynntils.com.wynntils.features.Gammabright.name
		feature.wynntils.com.wynntils.features.ItemHighlight.name
		feature.wynntils.com.wynntils.features.EmeraldPouchHotkey.name
		feature.wynntils.com.wynntils.features.MountHorseHotkey.name
		featureDebug.wynntils.com.wynntils.features.debug.ConnectionProgress.name
		feature.wynntils.com.wynntils.features.HealthPotionBlocker.name
		feature.wynntils.com.wynntils.features.MythicBlocker.name
	Loaded Overlays: 

-- Wynntils --
Details:
	In Development: Yes
	Loaded Features: 
		feature.wynntils.com.wynntils.features.SoulPointTimer.name
		featureDebug.wynntils.com.wynntils.features.debug.PacketDebugger.name
		feature.wynntils.com.wynntils.features.ItemStatInfo.name
		feature.wynntils.com.wynntils.features.PlayerGhostTransparency.name
		feature.wynntils.com.wynntils.features.IngredientPouchHotkey.name
		feature.wynntils.com.wynntils.features.WynncraftButton.name
		feature.wynntils.com.wynntils.features.ItemScreenshot.name
		feature.wynntils.com.wynntils.features.ItemGuess.name
		feature.wynntils.com.wynntils.features.DialogueOptionOverride.name
		featureDebug.wynntils.com.wynntils.features.debug.KeyBindTest.name
		feature.wynntils.com.wynntils.features.Gammabright.name
		feature.wynntils.com.wynntils.features.ItemHighlight.name
		feature.wynntils.com.wynntils.features.EmeraldPouchHotkey.name
		feature.wynntils.com.wynntils.features.MountHorseHotkey.name
		featureDebug.wynntils.com.wynntils.features.debug.ConnectionProgress.name
		feature.wynntils.com.wynntils.features.HealthPotionBlocker.name
		feature.wynntils.com.wynntils.features.MythicBlocker.name
	Loaded Overlays: 

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2097664944 bytes (2000 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 3.41
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1277
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.19
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.19
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 53150.28
	Virtual memory used (MB): 41348.75
	Swap memory total (MB): 36821.66
	Swap memory used (MB): 3875.45
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx8192m
	Loaded Shaderpack: (off)
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.77, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
```

```
Mods:
  [✔️] 3dskinlayers-fabric-1.4.6-mc1.18.2
  [✔️] AmbientEnvironment-fabric-1.18.2-7.0+19
  [✔️] architectury-4.9.84-fabric
  [✔️] audio_engine_tweaks-1.2.2 build 1
  [✔️] betterbeds-1.2.0
  [✔️] betterbiomeblend-1.18.2-1.3.5-fabric
  [✔️] BetterF3-1.2.5-Fabric-1.18.2
  [✔️] betterfpsdist-fabric-1.18-1.8
  [✔️] Blanket Client tweaks-1.0.4
  [✔️] bobby-3.1.1
  [✔️] cloth-config-6.2.57-fabric
  [✔️] continuity-2.0.1+1.18.2
  [✔️] CullLessLeaves-1.0.1
  [✔️] DynamicSoundFilters-1.3.0+1.18.2
  [✔️] easierchests-1.18.2-fabric0.47.10-1.7.0
  [✔️] enhancedblockentities-0.6+1.18.2
  [✔️] entityculling-fabric-mc1.18-1.5.1
  [✔️] fabric-api-0.58.0+1.18.2
  [✔️] fabric-language-kotlin-1.7.4+kotlin.1.6.21
  [✔️] fallingleaves-1.11.1+1.18.2
  [✔️] ferritecore-4.2.1-fabric
  [✔️] forgetmechunk-1.18.X-1.0.3
  [✔️] illuminations-1.10.4
  [✔️] indium-1.0.3+mc1.18.2
  [✔️] krypton-0.1.9
  [✔️] lambdabettergrass-1.2.3+1.18
  [✔️] lambdynamiclights-2.1.0+1.17
  [✔️] lazydfu-0.1.2
  [✔️] light-overlay-6.0.5
  [✔️] lithium-fabric-mc1.18.2-0.7.10.jar
  [✔️] Mambience-5.0.0+1.18.2
  [✔️] memoryleakfix-1.18.2-0.7.0
  [✔️] midnightcontrols-1.4.1+1.18
  [✔️] modmenu-3.2.2
  [✔️] moreculling-1.18.2-0.8.2
  [✔️] no-telemetry-1.3.0
  [✔️] reeses_sodium_options-mc1.18.2-1.4.2
  [✔️] replaymod-1.18.2-2.6.8
  [✔️] skiptransitions-1.3.2+1.18.x
  [✔️] sodium-extra-0.4.4+mc1.18.2-build.39
  [✔️] sodium-fabric-mc1.18.2-0.4.1replaymod.rev.23e83a1-far-render
  [✔️] starlight-1.0.2+fabric.89b8d9f
  [✔️] wynntils-1.1.0+313.MC1.18.2-fabric
  [✔️] XaerosWorldMap_1.28.0_Fabric_1.18.2
  [✔️] Zoomify-1.5.0
```

**Comment by 2No2Name** [comment]
You can probably work around this for now by adding the line
mixin.entity.collisions.unpushable_cramming=false
to the lithium.properties file in the config directory.

**Comment by Kepler-17c** [comment]
Thank you, I'll try that 👍

**Comment by 2No2Name** [comment]
The intended fix obviously doesn't work, needs another fix

**Comment by 2No2Name** [comment]
Exposes vanilla issue, because servers sending duplicate entities to the client isn't handled correctly in vanilla either

**Comment by 2No2Name** [comment]
Pushed another fix attempt https://github.com/CaffeineMC/lithium-fabric/actions/runs/3210983781 , the behavior is probably still bad, but not worse than vanilla.
