### ISSUE TITLE
Crash with newest version 0.9.0

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Lithium#397]
[21:01:15] [main/WARN]: Error loading class: me/jellysquid/mods/lithium/common/hopper/RemovalCounter (java.lang.ClassNotFoundException: me/jellysquid/mods/lithium/common/hopper/RemovalCounter)
[21:01:15] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [minecraft_server.jar:0.11.0]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig:20) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig:16) ~[?:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver:32) ~[?:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers:21) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries:66) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:50) ~[?:?]
	at net.minecraft.server.Main.main(Main:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3708 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig:9) ~[?:?]
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig:20) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig:16) ~[?:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver:32) ~[?:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers:21) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries:66) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:50) ~[?:?]
	at net.minecraft.server.Main.main(Main:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig:9) ~[?:?]
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig:20) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig:16) ~[?:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver:32) ~[?:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers:21) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries:66) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:50) ~[?:?]
	at net.minecraft.server.Main.main(Main:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for carpet-tis-addition.mixins.json:rule.largeBarrel.compat.lithium.BarrelBlockMixin from mod carpet-tis-addition during activity: [Transform -> Method resetLithiumHopperCache(Lnet/minecraft/class_1936;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;)V -> INVOKEINTERFACE -> me/jellysquid/mods/lithium/common/hopper/RemovalCounter::increaseRemovedCounter:()V]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig:9) ~[?:?]
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig:20) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig:16) ~[?:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver:32) ~[?:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers:21) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries:66) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:50) ~[?:?]
	at net.minecraft.server.Main.main(Main:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 4 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: me.jellysquid.mods.lithium.common.hopper.RemovalCounter
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:783) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:769) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:735) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig:9) ~[?:?]
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig:20) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig:16) ~[?:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver:32) ~[?:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers:21) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries:66) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:50) ~[?:?]
	at net.minecraft.server.Main.main(Main:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 4 more
Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.lithium.common.hopper.RemovalCounter
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:783) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:769) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:735) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig:9) ~[?:?]
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig:20) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig:16) ~[?:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver:32) ~[?:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers:21) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries:66) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:50) ~[?:?]
	at net.minecraft.server.Main.main(Main:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 4 more

**Comment by 2No2Name** [comment]
Wait for carpet-tis-addition to update in case you are using it.

**Comment by ghost** [comment]
Hello, yep I have this mod installed. If this is causing the problem - thank you for spotting it that fast.

**Comment by 2No2Name** [comment]
It was already known for weeks but TIS only updates when Lithium full releases are out, because otherwise it is too much work

**Comment by ghost** [comment]
Great, then they are already aware of that 😊
Thanks for the hard work, all.

**Comment by 2No2Name** [comment]
Not really an external issue but the agreement with the tis-addition authors is that they try fix it on their side first

**Comment by ghost** [comment]
huh. thats interesting. would u say it's easy to update Carpet TIS to the new versions of lithium?

**Comment by ghost** [comment]
The new version got released now: https://modrinth.com/mod/carpet-tis-addition/version/mc1.19.2-v1.40.1
This can be closed, works fine 🥰

**Comment by ghost** [comment]
oh sick. thanks for letting me know! :D
