### ISSUE TITLE
Incompatibility with Fabric API 0.64.0

### ISSUE THREAD

**Issue by srnyx** [jellysquid3/Lithium#401]
[Fabric Content Registries (v0)](https://github.com/FabricMC/fabric) is conflicting with [Lithium](https://github.com/CaffeineMC/lithium-fabric).

### Version

Lithium 0.9.1 for 1.19.2

### Reproduction Steps

1. Install Fabric 0.64.0 for 1.19.2
2. Install Lithium 0.9.1 for 1.19.2
3. Try to launch the game

### Stacktrace
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE_ASSIGN") on net/minecraft/class_14::getCommonNodeType with priority 999 cannot inject into net/minecraft/class_14::method_58(Lnet/minecraft/class_1922;Lnet/minecraft/class_2338;)Lnet/minecraft/class_7; merged by me.jellysquid.mods.lithium.mixin.ai.pathing.LandPathNodeMakerMixin with priority 1000 [PREINJECT Applicator Phase -> fabric-content-registries-v0.mixins.json:LandPathNodeMakerMixin from mod fabric-content-registries-v0 -> Prepare Injections ->  -> handler$bhf000$getCommonNodeType(Lnet/minecraft/class_1922;Lnet/minecraft/class_2338;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2680;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.audit(MixinProcessor.java:254)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.audit(MixinTransformer.java:171)
	at org.spongepowered.asm.mixin.MixinEnvironment.audit(MixinEnvironment.java:1425)
	at ca.fxco.memoryleakfix.MemoryLeakFix.forceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFix.java:30)
	at net.minecraft.client.main.Main.handler$eka000$loadAllMixinsThenShouldRenderAsync(Main.java:526)
	at net.minecraft.client.main.Main.method_44604(Main.java:220)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

### Mod list
```
- advanced-tooltips 1.6.0+1.19
- advanced-tooltips-core 1.6.0 via advanced-tooltips
- advanced_runtime_resource_pack 0.6.2 via enhancedblockentities
- advancementinfo 1.19.1-fabric0.58.5-1.3.1
- advdebug 2.3.0
- animatica 0.5+1.19
- appleskin 2.4.1+mc1.19
- architectury 6.2.46
- audio_engine_tweaks 1.2.3
- authme 4.2.0
- better-dark-mode 2.1.0
- betterfpsdist 1.19.1-1.9
- bettertaskbar 1.5
- betterthirdperson 1.8.1
- blanket-client-tweaks 1.1.2
- blockify 1.2.4
- blue_endless_jankson 1.2.1 via owo
- boatiview 0.0.4
- bobberbegone 1.0.0+1.16.5-1.19.x
- boostedbrightness 2.1.2
- brb 1.6.0
- caffeineconfig 1.0.0+1.17 via sodium-extra
- capes 1.4.5+1.19
- cem 0.7.1
- chat_heads 0.7.1
- chesttracker 1.1.17
- citresewn 1.1.2+1.19.2
- citresewn-defaults 1.1.2+1.19.2 via citresewn
- clean-logs 1.1.0
- cleardespawn 1.1.9
- cloth-basic-math 0.6.1 via cloth-config
- cloth-config 8.2.88
- coat 1.0.0-beta.17+mc22w17a via completeconfig
- colormatic 3.1.2+mc.1.19
- com_github_llamalad7_mixinextras 0.0.12 via debugify
- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
- completeconfig 2.0.0
- completeconfig-base 2.0.0 via completeconfig
- completeconfig-gui-cloth 2.0.0 via completeconfig
- completeconfig-gui-coat 2.0.0 via completeconfig
- conditional-mixin 0.3.0 via cull-less-leaves
- continuity 2.0.1+1.19
- controlling 10.0+6
- crowdin-translate 1.4+1.19 via blockify
- cull-less-leaves 1.0.4
- debugify 2.7.1
- dynamicfps 2.2.0
- effective 1.3
- enhanced_attack_indicator 1.0.4+1.19
- enhancedblockentities 0.7.1+1.19
- entity_texture_features 4.1.1
- entityculling 1.5.2-mc1.19
- essential-container 1.0.0
- essential-loader 1.0.0 via essential-container
- exordium 1.0.1-mc1.19.2
- extrasounds 2.3.1+1.19.2-1.19.1
- fabric-api 0.64.0+1.19.2
- fabric-api-base 0.4.12+93d8cb8290 via authme
- fabric-api-lookup-api-v1 1.6.10+93d8cb8290 via fabric-api
- fabric-biome-api-v1 9.0.18+c6af733c90 via fabric-api
- fabric-blockrenderlayer-v1 1.1.21+c6af733c90 via fabric-api
- fabric-client-tags-api-v1 1.0.2+b35fea8390 via fabric-api
- fabric-command-api-v1 1.2.12+f71b366f90 via fabric-api
- fabric-command-api-v2 2.1.8+93d8cb8290 via fabric-api
- fabric-commands-v0 0.2.29+df3654b390 via fabric-api
- fabric-containers-v0 0.1.35+df3654b390 via fabric-api
- fabric-content-registries-v0 3.4.0+6064db2a90 via fabric-api
- fabric-convention-tags-v1 1.1.2+93d8cb8290 via fabric-api
- fabric-crash-report-info-v1 0.2.6+aeb40ebe90 via fabric-api
- fabric-data-generation-api-v1 5.2.2+b598f4ac90 via fabric-api
- fabric-dimensions-v1 2.1.32+0dd10df690 via fabric-api
- fabric-entity-events-v1 1.4.19+9ff28f4090 via fabric-api
- fabric-events-interaction-v0 0.4.29+c6af733c90 via fabric-api
- fabric-events-lifecycle-v0 0.2.29+df3654b390 via fabric-api
- fabric-game-rule-api-v1 1.0.22+c6af733c90 via fabric-api
- fabric-item-api-v1 1.5.8+93d8cb8290 via fabric-api
- fabric-item-groups-v0 0.3.32+70efcffe90 via fabric-api
- fabric-key-binding-api-v1 1.0.22+aaaf9d3390 via fabric-api
- fabric-keybindings-v0 0.2.20+df3654b390 via fabric-api
- fabric-language-kotlin 1.8.5+kotlin.1.7.20
- fabric-lifecycle-events-v1 2.2.0+33ffe9ec90 via authme
- fabric-loot-api-v2 1.1.6+83a8659290 via fabric-api
- fabric-loot-tables-v1 1.1.9+9e7660c690 via fabric-api
- fabric-message-api-v1 5.0.4+93d8cb8290 via fabric-api
- fabric-mining-level-api-v1 2.1.17+33fbc73890 via fabric-api
- fabric-models-v0 0.3.18+c6af733c90 via fabric-api
- fabric-networking-api-v1 1.2.5+c6af733c90 via fabric-api
- fabric-networking-v0 0.3.22+df3654b390 via fabric-api
- fabric-object-builder-api-v1 4.0.14+93d8cb8290 via fabric-api
- fabric-particles-v1 1.0.11+79adfe0a90 via fabric-api
- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
- fabric-registry-sync-v0 0.9.26+c6af733c90 via fabric-api
- fabric-renderer-api-v1 1.0.12+c0ae659d90 via fabric-api
- fabric-renderer-indigo 0.6.14+aeb40ebe90 via fabric-api
- fabric-renderer-registries-v1 3.2.21+df3654b390 via fabric-api
- fabric-rendering-data-attachment-v1 0.3.15+aeb40ebe90 via fabric-api
- fabric-rendering-fluids-v1 3.0.8+c6af733c90 via fabric-api
- fabric-rendering-v0 1.1.23+df3654b390 via fabric-api
- fabric-rendering-v1 1.11.0+73145abb90 via fabric-api
- fabric-resource-conditions-api-v1 2.1.0+aae9039d90 via fabric-api
- fabric-resource-loader-v0 0.7.2+70efcffe90 via fabric-api
- fabric-screen-api-v1 1.0.27+93d8cb8290 via fabric-api
- fabric-screen-handler-api-v1 1.3.1+1cc24b1b90 via fabric-api
- fabric-sound-api-v1 1.0.0+c4f28df590 via fabric-api
- fabric-textures-v0 1.0.21+aeb40ebe90 via fabric-api
- fabric-transfer-api-v1 2.1.1+93d8cb8290 via fabric-api
- fabric-transitive-access-wideners-v1 1.3.1+42d99c3290 via fabric-api
- fabrication 3.0.3+1.19
- fabricloader 0.14.9
- fallingleaves 1.12.2+1.19.2
- faster_entity_animations 1.5.6
- fastload 1.2.1
- ferritecore 4.2.1
- gbfabrictools 1.3.4+1.19 via grid
- grid 1.19.1-fabric0.58.5-1.6.7
- holdthatchunk 1.1.1
- horsebuff 2.0.1
- horsestatsvanilla 4.2.2
- indium 1.0.9+mc1.19.2
- inventoryprofilesnext 1.8.2
- io_github_douira_glsl-transformer 1.0.0-pre21.2 via iris
- io_gitlab_jfronny_muscript 2022.7.4+11-13-3 via respackopts
- iris 1.4.0
- isometric-renders 0.4.0+1.19
- isxander-main-menu-credits 1.1.1
- jankson 4.1.1+j1.2.1 via libgui
- java 17
- kirin 1.11.1 via presencefootsteps
- krypton 0.2.1
- lambdynlights 2.1.2+1.19
- lazydfu 0.1.3
- lib39-deferral 1.1.1 via fabrication
- libgui 6.0.0+1.19 via horsestatsvanilla
- libipn 1.0.3
- libjf 3.2.0
- libjf-base 3.2.0 via libjf
- libjf-config-core-v1 3.2.0 via libjf
- libjf-config-legacy-shim 3.2.0 via libjf
- libjf-config-reflect-v1 3.2.0 via libjf
- libjf-config-ui-tiny-v1 3.2.0 via libjf
- libjf-data-manipulation-v0 3.2.0 via libjf
- libjf-data-v0 3.2.0 via libjf
- libjf-translate-v1 3.2.0 via libjf
- libjf-unsafe-v0 3.2.0 via libjf
- libjf-web-v0 3.2.0 via libjf
- libninepatch 1.1.0 via libgui
- lithium 0.9.1
- malilib 0.13.0
- memoryleakfix 1.19.1-0.7.0
- microdurability 0.3.6+1.19
- microdurability-core 0.3.6 via microdurability
- midnightlib 0.5.2 via blockify
- minecraft 1.19.2
- minihud 0.23.3
- mixin-conflict-helper 1.2.0
- moderate-loading-screen 1.1.3+1.19
- modmenu 4.0.6
- moreculling 1.19.1-0.10.0
- no_fog 1.3.1+1.16.5-1.19.2
- nochatreports 1.19.2-v1.13.9
- notenoughanimations 1.6.1
- notenoughcrashes 4.1.8+1.19.2
- omega-config 1.2.3-1.18.1 via capes
- ordinarytweaks 1.3.1
- org_anarres_jcpp 1.4.14 via iris
- org_antlr_antlr4-runtime 4.10.1 via iris
- org_apache_httpcomponents_httpmime 4.5.10 via entity_texture_features
- org_jetbrains_kotlin_kotlin-reflect 1.7.20 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 1.7.20 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.20 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.20 via fabric-language-kotlin
- org_jetbrains_kotlinx_atomicfu-jvm 0.18.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
- org_joml_joml 1.10.4 via sodium
- owo 0.8.5+1.19
- physicsmod 2.8.13
- presencefootsteps 1.6.2
- pride 1.1.2+1.19 via fabrication
- reeses-sodium-options 1.4.7+mc1.19.2-build.59
- replaymod 1.19.1-2.6.8
- resclone 1.10.0
- respackopts 4.0.2
- smoothboot 1.19-1.7.1
- smoothswapping 0.4.5
- sodium 0.4.4+build.18
- sodium-extra 0.4.11+mc1.19.2-build.68
- soundcategories 1.2.4+1.19 via extrasounds
- spark 1.9.42
- spruceui 4.0.0+1.19 via enhancedblockentities
- sspb 3.1.0
- starlight 1.1.1+fabric.ae22326
- statuseffecttimer 1.1.1+1.19
- togglenametags 2.0.1
- unglow 1.1
- vmp 0.2.0+beta.7.0
- voicechat 1.19.2-2.3.10
- waveycapes 1.2.1
- whereisit 1.14.11 via chesttracker
- whoami 1.0
- worldmesher 0.2.12+1.19 via isometric-renders
- xaerobetterpvpfair 22.14.1
- yosbr 0.1.1
- essential 10597+deploy-staging+gdcc76310f
- universalcraft 242
- org_jetbrains_annotations 13.0
- elementa 554
- vigilance 258
```

### Game info
Minecraft Version: 1.19.2
Fabric Loader Version: 0.14.9

*Message autogenerated using [MixinConflictHelper](https://github.com/isXander/MixinConflictHelper)*

**Comment by CDAGaming** [comment]
Same issue on my end, Villagers also fail to render in addition to this

**Comment by 2No2Name** [comment]
Should be fixed in this build https://github.com/CaffeineMC/lithium-fabric/actions/runs/3275429667
