### ISSUE TITLE
Crash with Hopper+ mod v3.3.2-1.19.1

### ISSUE THREAD

**Issue by bvhfve** [jellysquid3/Lithium#406]
*Message autogenerated using [MixinConflictHelper](https://github.com/isXander/MixinConflictHelper)*
[Hopper Plus](https://www.curseforge.com/minecraft/mc-mods/hopper) is conflicting with [Lithium].

## Stacktrace
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_2614::a with priority 1000 cannot inject into net/minecraft/class_2614::method_11237(Lnet/minecraft/class_1937;Lnet/minecraft/class_2615;)Ljava/util/List; merged by me.jellysquid.mods.lithium.mixin.entity.hopper_minecart.HopperBlockEntityMixin with priority 1000 [PREINJECT Applicator Phase -> hplus.mixins.json:HopperBlockEntityMixin from mod hplus -> Prepare Injections ->  -> redirect$dek000$a(Lnet/minecraft/class_2615;)Lnet/minecraft/class_265; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_2246.<clinit>(class_2246.java:471)
	at net.minecraft.class_5872.<clinit>(class_5872.java:9)
	at net.minecraft.class_5871.method_33968(class_5871.java:20)
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
	at net.minecraft.class_5871.<clinit>(class_5871.java:16)
	at net.minecraft.class_2939.<clinit>(class_2939.java:32)
	at net.minecraft.class_5463.<clinit>(class_5463.java:21)
	at net.minecraft.class_5458.method_30572(class_5458.java:66)
	at net.minecraft.class_5458.method_44104(class_5458.java:98)
	at net.minecraft.class_5458.method_30566(class_5458.java:105)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.class_5458.<clinit>(class_5458.java:104)
	at net.minecraft.class_2378.<clinit>(class_2378.java:326)
	at net.minecraft.class_2966.method_12851(class_2966.java:50)
	at net.minecraft.client.main.Main.method_44604(Main.java:161)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

## Mod list
```
- advanced-xray-fabric 1.19-1.1.0-build.12
- advanced_runtime_resource_pack 0.6.2 via enhancedblockentities
- advancementinfo 1.19.1-fabric0.58.5-1.3.1
- animatica 0.5+1.19
- antighost 1.19.1-fabric0.58.5-1.1.5
- apples 1.19
- architectury 6.3.49
- attributefix 17.1.3
- autoclicker-fabric 1.19.2-1.4.2-build.19
- badpackets 0.2.0
- bendy-lib 2.1.1
- bettercombat 1.4.5+1.19
- bettermounthud 1.2.0
- blue_endless_jankson 1.2.1 via jankson
- borderlessmining 1.1.5+1.19
- caffeineconfig 1.0.0+1.17 via sodium-extra
- cardinal-components-base 5.0.0-beta.1 via trinkets
- cardinal-components-entity 5.0.0-beta.1 via trinkets
- carpet 1.4.84
- carpet-fixes 1.19-1.12.2
- cem 0.7.1_S6_1.19
- charmofundying 6.0.0+1.19.2
- citresewn 1.1.2+1.19.2
- citresewn-defaults 1.1.2+1.19.2 via citresewn
- clickadv 2.9
- cloth-basic-math 0.6.1 via cloth-config
- cloth-config 8.2.88
- clumps 9.0.0+11
- coat 1.0.0-beta.17+mc22w17a via completeconfig
- colormatic 3.1.2+mc.1.19
- com_github_llamalad7_mixinextras 0.0.12 via cull-less-leaves
- com_google_guava_guava 31.1-jre via fabrizoom
- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
- com_typesafe_config 1.4.2 via fabrizoom
- completeconfig 2.0.0
- completeconfig-base 2.0.0 via cem
- completeconfig-gui-cloth 2.0.0 via cem
- completeconfig-gui-coat 2.0.0 via completeconfig
- conditional-mixin 0.3.1 via carpet-fixes
- config2brigadier 1.2.1 via simplevillagers
- continuity 2.0.1+1.19
- copperhopper 0.0.11+1.19.2
- crowdin-translate 1.4+1.19 via antighost
- cull-less-leaves 1.0.6
- dark-enchanting 1.0.0+1.19.1
- debugify 2.7.1
- display_case 1.0.3
- dragonloot 1.1.2
- dynamicfps 2.2.0
- enhancedblockentities 0.7.1+1.19
- entity_texture_features 4.1.1
- entityculling 1.5.2-mc1.19
- error_notifier 1.0.9 via roughlyenoughitems
- fabric-api 0.63.0+1.19.2
- fabric-api-base 0.4.12+93d8cb8290 via fabric-api
- fabric-api-lookup-api-v1 1.6.10+93d8cb8290 via fabric-api
- fabric-biome-api-v1 9.0.18+c6af733c90 via fabric-api
- fabric-blockrenderlayer-v1 1.1.21+c6af733c90 via fabric-api
- fabric-client-tags-api-v1 1.0.2+b35fea8390 via fabric-api
- fabric-command-api-v1 1.2.12+f71b366f90 via fabric-api
- fabric-command-api-v2 2.1.8+93d8cb8290 via fabric-api
- fabric-commands-v0 0.2.29+df3654b390 via fabric-api
- fabric-containers-v0 0.1.35+df3654b390 via fabric-api
- fabric-content-registries-v0 3.3.2+624e468e90 via fabric-api
- fabric-convention-tags-v1 1.1.2+93d8cb8290 via fabric-api
- fabric-crash-report-info-v1 0.2.6+aeb40ebe90 via fabric-api
- fabric-data-generation-api-v1 5.2.1+b598f4ac90 via fabric-api
- fabric-dimensions-v1 2.1.32+0dd10df690 via fabric-api
- fabric-entity-events-v1 1.4.19+9ff28f4090 via fabric-api
- fabric-events-interaction-v0 0.4.29+c6af733c90 via fabric-api
- fabric-events-lifecycle-v0 0.2.29+df3654b390 via fabric-api
- fabric-game-rule-api-v1 1.0.22+c6af733c90 via fabric-api
- fabric-item-api-v1 1.5.8+93d8cb8290 via fabric-api
- fabric-item-groups-v0 0.3.31+0c4b8d3c90 via fabric-api
- fabric-key-binding-api-v1 1.0.22+aaaf9d3390 via fabric-api
- fabric-keybindings-v0 0.2.20+df3654b390 via fabric-api
- fabric-language-kotlin 1.8.5+kotlin.1.7.20
- fabric-lifecycle-events-v1 2.2.0+33ffe9ec90 via fabric-api
- fabric-loot-api-v2 1.1.5+83a8659290 via fabric-api
- fabric-loot-tables-v1 1.1.8+9e7660c690 via fabric-api
- fabric-message-api-v1 5.0.4+93d8cb8290 via fabric-api
- fabric-mining-level-api-v1 2.1.16+33fbc73890 via fabric-api
- fabric-models-v0 0.3.18+c6af733c90 via fabric-api
- fabric-networking-api-v1 1.2.5+c6af733c90 via fabric-api
- fabric-networking-v0 0.3.22+df3654b390 via fabric-api
- fabric-object-builder-api-v1 4.0.13+93d8cb8290 via fabric-api
- fabric-particles-v1 1.0.11+79adfe0a90 via fabric-api
- fabric-permissions-api-v0 0.1-SNAPSHOT via simplevillagers
- fabric-registry-sync-v0 0.9.26+c6af733c90 via fabric-api
- fabric-renderer-api-v1 1.0.12+c0ae659d90 via fabric-api
- fabric-renderer-indigo 0.6.14+aeb40ebe90 via fabric-api
- fabric-renderer-registries-v1 3.2.21+df3654b390 via fabric-api
- fabric-rendering-data-attachment-v1 0.3.15+aeb40ebe90 via fabric-api
- fabric-rendering-fluids-v1 3.0.8+c6af733c90 via fabric-api
- fabric-rendering-v0 1.1.23+df3654b390 via fabric-api
- fabric-rendering-v1 1.11.0+73145abb90 via fabric-api
- fabric-resource-conditions-api-v1 2.1.0+aae9039d90 via fabric-api
- fabric-resource-loader-v0 0.7.1+0c4b8d3c90 via fabric-api
- fabric-screen-api-v1 1.0.27+93d8cb8290 via fabric-api
- fabric-screen-handler-api-v1 1.3.1+1cc24b1b90 via fabric-api
- fabric-sound-api-v1 1.0.0+c4f28df590 via fabric-api
- fabric-textures-v0 1.0.21+aeb40ebe90 via fabric-api
- fabric-transfer-api-v1 2.1.1+93d8cb8290 via fabric-api
- fabric-transitive-access-wideners-v1 1.3.1+42d99c3290 via fabric-api
- fabricloader 0.14.9
- fabrishot 1.9.1
- fabrizoom 1.2.0-dev
- farsight 1.19-2.1
- ferritecore 4.2.1
- flytre_lib 1.8.8
- greater_eye 1.4.18
- hplus 3.3.2
- indium 1.0.9+mc1.19.2
- inmis 2.7.1-1.19
- inventoryhud 3.4.2
- io_github_douira_glsl-transformer 1.0.0-pre21.2 via iris
- io_leangen_geantyref_geantyref 1.3.12 via fabrizoom
- iris 1.4.0
- isxander-main-menu-credits 1.1.1
- itemmodelfix 1.0.3+1.19
- jankson 4.1.1+j1.2.1 via libgui
- java 17
- kibe 1.9.10-BETA+1.19
- lambdabettergrass 1.3.0+1.19
- lambdynlights 2.1.2+1.19
- languagereload 1.3.2
- lazydfu 0.1.3
- libgui 6.0.0+1.19 via dark-enchanting
- libninepatch 1.1.0 via libgui
- limitless 1.6.8-2
- lithium 0.10.0
- megane 8.3.0
- megane-api 8.3.0 via megane
- megane-fabric-transfer 8.3.0 via megane
- megane-kibe 8.3.0 via megane
- megane-runtime 8.3.0 via megane
- megane-vanilla 8.3.0 via megane
- memoryleakfix 1.19.1-0.7.0
- merenc 1.10
- midnightcontrols 1.7.0+1.19
- midnightlib 0.6.1 via midnightcontrols
- minecraft 1.19.2
- mixin-conflict-helper 1.2.0
- mixintrace 1.1.1+1.17
- modmenu 4.0.6
- morechathistory 1.1.1
- moreculling 1.19.1-0.10.0
- net_auoeke_reflect 5.2.2 via limitless
- net_auoeke_unsafe 1.7.2 via limitless
- net_objecthunter_exp4j 0.4.8 via spoornarmorattributes
- nochatreports 1.19.2-v1.13.9
- nofade 1.18-2.0.1
- omega-config 1.2.3-1.18.1 via dark-enchanting
- optigui 1.1.6
- org_anarres_jcpp 1.4.14 via iris
- org_antlr_antlr4-runtime 4.10.1 via iris
- org_apache_commons_commons-text 1.9 via optigui
- org_apache_httpcomponents_httpmime 4.5.10 via entity_texture_features
- org_aperlambda_lambdajcommon 1.8.1 via midnightcontrols
- org_jetbrains_kotlin_kotlin-reflect 1.7.20 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 1.7.20 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.20 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.20 via fabric-language-kotlin
- org_jetbrains_kotlinx_atomicfu-jvm 0.18.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
- org_joml_joml 1.10.4 via sodium
- org_spongepowered_configurate-core 4.1.2 via fabrizoom
- org_spongepowered_configurate-extra-kotlin 4.1.2 via fabrizoom
- org_spongepowered_configurate-hocon 4.1.2 via fabrizoom
- packet_tweaker 0.3.0+1.18.2 via server_translations_api
- player-animator 0.4.0-test1
- playerabilitylib 1.6.0 via kibe
- polymer 0.2.10+1.19.1 via simplevillagers
- polymer-registry-sync-manipulator 0.0.1+1.19.1 via polymer
- pride 1.1.2+1.19 via lambdynlights
- pugh_tools 1.3.22 via treeaxe
- puzzle 1.4.0-1.19
- puzzle-base 1.4.0-1.19 via puzzle
- puzzle-gui 1.4.0-1.19 via puzzle
- puzzle-models 1.4.0-1.19 via puzzle
- puzzle-splashscreen 1.4.0-1.19 via puzzle
- reeses-sodium-options 1.4.7+mc1.19.2-build.59
- ring_of_enderchest 1.3.14
- ring_of_growth 1.3.15
- ring_of_teleport 1.2.14
- roughlyenoughitems 9.1.555
- server_translations_api 1.4.16+1.19 via simplevillagers
- sgui 1.1.3+1.19.1 via simplevillagers
- shulkerboxtooltip 3.2.1+1.19.2
- simpletech 2.3.0
- simplevillagers 1.4.1
- smoothboot 1.19-1.7.1
- sodium 0.4.4+build.18
- sodium-extra 0.4.11+mc1.19.2-build.68
- spawnermod 1.2.0
- spoornarmorattributes 2.0.6-1.19
- spoornweaponattributes 4.0.9-1.19
- spruceui 4.0.0+1.19 via enhancedblockentities
- stacc 1.3.4 via stacker
- stacker 3.0.2-1.19.x
- starlight 1.1.1+fabric.ae22326
- tlskincape 1.27
- toms_storage 1.4.3
- treeaxe 1.2.23
- trinkets 3.4.0
- wands 2.6.3_release
- wthit 5.13.3
- xaerominimap 22.16.0
- xaeroworldmap 1.28.1
- yet-another-config-lib 1.5.0
- yosbr 0.1.1

## Game info
Minecraft Version: 1.19.2
Fabric Loader Version: 0.14.9

----------------------------------

### Version

> lithium version: lithium-fabric-mc1.19.2-0.10.0

### Reproduction Steps
> Minecraft crashed right after entering the game from client

### Crash Report File

> Upload your crash report file as an attachment to this issue (drag-and-drop) or to a service such as GitHub
> Gist (paste a link) and replace this section. This information is critical in resolving your issue!
> 
> Tip: Messages like "Exit code 0" from your launcher are not what you're looking for. If your launcher does not
> provide a button to view the most recent crash report, check your game's "crash-reports" folder for the most recent
> crash report file.
> [latest.log](https://github.com/CaffeineMC/lithium-fabric/files/9894086/latest.log)
> https://pastebin.com/ts7fMX0X (latest.log again just in case something goes wrong)

**Comment by 2No2Name** [comment]
Hopper+ is not open source, therefore I cannot investigate the issue further. Please report to the Hopper+ authors instead.

You can work around the issue for now by adding the line
mixin.entity.hopper_minecart=false
to the lithium.properties file in the config folder.
