### ISSUE TITLE
Some chunks stop loading when using `lithium` alongside `moreculling`

### ISSUE THREAD

**Issue by ChristopherHaws** [jellysquid3/Lithium#420]
### Version Information
lithium-fabric-mc1.19.2-0.10.2
moreculling-1.19.1-0.10.0

### Expected Behavior
All the chunks should load.

### Actual Behavior
Some chunks don't load

### Reproduction Steps
Use `lithium` alongside `moreculling`.

### Other Information
Full Logs: https://mclo.gs/UvtOzb1

Stacktrace:
```
[14:34:04] [Chunk Render Task Executor #5/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: net.minecraft.class_148: Tessellating block in world - Indium Renderer
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:61)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$fmj000$onRenderBlock(ChunkRenderRebuildTask.java:1054)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:99)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:285)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:325)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.computeIfAbsent(Object, it.unimi.dsi.fastutil.objects.Object2BooleanFunction)" because "this.stateTranslucencyCache" is null
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at net.minecraft.class_1095.hasTextureTranslucency(class_1095.java:1542)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at net.minecraft.class_2248.shouldAttemptToCull(class_2248.java:5680)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.shouldAttemptToCull(class_4970.java:4674)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at ca.fxco.moreculling.utils.CullingUtils.shouldDrawSideCulling(CullingUtils.java:46)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.occlusion.BlockOcclusionCache.handler$hbb000$useMoreCulling(BlockOcclusionCache.java:1041)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.occlusion.BlockOcclusionCache.shouldDrawSide(BlockOcclusionCache.java:36)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.TerrainBlockRenderInfo.shouldDrawFace(TerrainBlockRenderInfo.java:45)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.BaseFallbackConsumer.renderQuad(BaseFallbackConsumer.java:108)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.BaseFallbackConsumer.accept(BaseFallbackConsumer.java:92)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.BaseFallbackConsumer.accept(BaseFallbackConsumer.java:57)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:1074)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at net.minecraft.class_1095.emitBlockQuads(class_1095.java:1084)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:56)
[14:34:04] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	... 5 more
[14:34:04] [Chunk Render Task Executor #1/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.computeIfAbsent(Object, it.unimi.dsi.fastutil.objects.Object2BooleanFunction)" because "this.stateTranslucencyCache" is null
[14:34:04] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at net.minecraft.class_1095.hasTextureTranslucency(class_1095.java:1542)
[14:34:04] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at net.minecraft.class_2248.shouldAttemptToCull(class_2248.java:5680)
[14:34:04] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.shouldAttemptToCull(class_4970.java:4674)
[14:34:04] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at ca.fxco.moreculling.utils.CullingUtils.shouldDrawSideCulling(CullingUtils.java:47)
[14:34:04] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.occlusion.BlockOcclusionCache.handler$hbb000$useMoreCulling(BlockOcclusionCache.java:1041)
[14:34:04] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.occlusion.BlockOcclusionCache.shouldDrawSide(BlockOcclusionCache.java:36)
[14:34:04] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:71)
[14:34:04] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$fmj000$onRenderBlock(ChunkRenderRebuildTask.java:1050)
[14:34:04] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:99)
[14:34:04] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:285)
[14:34:04] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:325)
[14:34:04] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:34:06] [Chunk Render Task Executor #3/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: net.minecraft.class_148: Tessellating block in world - Indium Renderer
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:61)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$fmj000$onRenderBlock(ChunkRenderRebuildTask.java:1054)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:99)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:285)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:325)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.computeIfAbsent(Object, it.unimi.dsi.fastutil.objects.Object2BooleanFunction)" because "this.stateTranslucencyCache" is null
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at net.minecraft.class_1095.hasTextureTranslucency(class_1095.java:1542)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at net.minecraft.class_2248.shouldAttemptToCull(class_2248.java:5680)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.shouldAttemptToCull(class_4970.java:4674)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at ca.fxco.moreculling.utils.CullingUtils.shouldDrawSideCulling(CullingUtils.java:46)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.occlusion.BlockOcclusionCache.handler$hbb000$useMoreCulling(BlockOcclusionCache.java:[1041](https://mclo.gs/UvtOzb1#L1041))
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.occlusion.BlockOcclusionCache.shouldDrawSide(BlockOcclusionCache.java:36)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.TerrainBlockRenderInfo.shouldDrawFace(TerrainBlockRenderInfo.java:45)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.BaseFallbackConsumer.renderQuad(BaseFallbackConsumer.java:108)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.BaseFallbackConsumer.accept(BaseFallbackConsumer.java:92)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.BaseFallbackConsumer.accept(BaseFallbackConsumer.java:57)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at net.minecraft.class_1095.emitBlockQuads(class_1095.java:1092)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:56)
[14:34:06] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	... 5 more
[14:34:06] [Chunk Render Task Executor #2/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: net.minecraft.class_148: Tessellating block in world - Indium Renderer
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:61)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$fmj000$onRenderBlock(ChunkRenderRebuildTask.java:[1054](https://mclo.gs/UvtOzb1#L1054))
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:99)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:285)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:325)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.computeIfAbsent(Object, it.unimi.dsi.fastutil.objects.Object2BooleanFunction)" because "this.stateTranslucencyCache" is null
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at net.minecraft.class_1095.hasTextureTranslucency(class_1095.java:1542)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at net.minecraft.class_2248.shouldAttemptToCull(class_2248.java:5680)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.shouldAttemptToCull(class_4970.java:4674)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at ca.fxco.moreculling.utils.CullingUtils.shouldDrawSideCulling(CullingUtils.java:46)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.occlusion.BlockOcclusionCache.handler$hbb000$useMoreCulling(BlockOcclusionCache.java:1041)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.occlusion.BlockOcclusionCache.shouldDrawSide(BlockOcclusionCache.java:36)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.TerrainBlockRenderInfo.shouldDrawFace(TerrainBlockRenderInfo.java:45)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.BaseFallbackConsumer.renderQuad(BaseFallbackConsumer.java:108)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.BaseFallbackConsumer.accept(BaseFallbackConsumer.java:92)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.BaseFallbackConsumer.accept(BaseFallbackConsumer.java:57)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at net.minecraft.class_1095.emitBlockQuads(class_1095.java:1092)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:56)
[14:34:06] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	... 5 more
[14:34:06] [Render thread/INFO]: Joining syncmatica server with local version 0.3.5 and server version 0.3.5
[14:34:06] [Chunk Render Task Executor #1/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: net.minecraft.class_148: Tessellating block in world - Indium Renderer
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:61)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$fmj000$onRenderBlock(ChunkRenderRebuildTask.java:1054)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:99)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:285)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:325)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.computeIfAbsent(Object, it.unimi.dsi.fastutil.objects.Object2BooleanFunction)" because "this.stateTranslucencyCache" is null
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at net.minecraft.class_1095.hasTextureTranslucency(class_1095.java:1542)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at net.minecraft.class_2248.shouldAttemptToCull(class_2248.java:5680)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.shouldAttemptToCull(class_4970.java:4674)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at ca.fxco.moreculling.utils.CullingUtils.shouldDrawSideCulling(CullingUtils.java:46)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.occlusion.BlockOcclusionCache.handler$hbb000$useMoreCulling(BlockOcclusionCache.java:1041)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.occlusion.BlockOcclusionCache.shouldDrawSide(BlockOcclusionCache.java:36)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.TerrainBlockRenderInfo.shouldDrawFace(TerrainBlockRenderInfo.java:45)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.BaseFallbackConsumer.renderQuad(BaseFallbackConsumer.java:108)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.BaseFallbackConsumer.accept(BaseFallbackConsumer.java:92)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.BaseFallbackConsumer.accept(BaseFallbackConsumer.java:57)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at net.minecraft.class_[1087](https://mclo.gs/UvtOzb1#L1087).emitBlockQuads(class_1087.java:545)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at net.minecraft.class_1095.emitBlockQuads(class_1095.java:1092)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:56)
[14:34:06] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	... 5 more

**Comment by ChristopherHaws** [comment]
I'm dumb and opened this in the wrong repo xD Sorry! This was meant for indium :P
