### ISSUE TITLE
Crash with Hopper+ mod on launcher startup (again)

### ISSUE THREAD

**Issue by bvhfve** [jellysquid3/Lithium#451]
### Version
lithium-fabric-mc1.19.2-0.10.4

### Crash Report Template 
*Message autogenerated using [MixinConflictHelper](https://github.com/isXander/MixinConflictHelper)*
[Hopper Plus](https://www.curseforge.com/minecraft/mc-mods/hopper) is conflicting with [Lithium](https://github.com/CaffeineMC/lithium-fabric).

## Stacktrace
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_2614::hplus$getSuctionHitbox with priority 1000 cannot inject into net/minecraft/class_2614::method_11237(Lnet/minecraft/class_1937;Lnet/minecraft/class_2615;)Ljava/util/List; merged by me.jellysquid.mods.lithium.mixin.entity.hopper_minecart.HopperBlockEntityMixin with priority 1000 [PREINJECT Applicator Phase -> hplus.mixins.json:HopperBlockEntityMixin from mod hplus -> Prepare Injections ->  -> redirect$eho000$hplus$getSuctionHitbox(Lnet/minecraft/class_2615;)Lnet/minecraft/class_265; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_2246.<clinit>(class_2246.java:471)
	at net.minecraft.class_5872.<clinit>(class_5872.java:9)
	at net.minecraft.class_5871.method_33968(class_5871.java:20)
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
	at net.minecraft.class_5871.<clinit>(class_5871.java:16)
	at net.minecraft.class_2939.<clinit>(class_2939.java:32)
	at net.minecraft.class_5463.<clinit>(class_5463.java:21)
	at net.minecraft.class_5458.method_30572(class_5458.java:66)
	at net.minecraft.class_5458.method_44104(class_5458.java:98)
	at net.minecraft.class_5458.method_30566(class_5458.java:105)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.class_5458.<clinit>(class_5458.java:104)
	at net.minecraft.class_2378.<clinit>(class_2378.java:326)
	at net.minecraft.class_2966.method_12851(class_2966.java:50)
	at net.minecraft.client.main.Main.method_44604(Main.java:161)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

## Mod list
```
- adapaxels 1.4.0+1.19.2
- advanced-xray-fabric 1.19-1.1.0-build.12
- advanced_runtime_resource_pack 0.6.2 via enhancedblockentities
- advancementinfo 1.19.1-fabric0.58.5-1.3.1
- advdebug 2.3.0
- allarrowsinfinityfix 1.4
- alloy_forgery 2.0.19+1.19
- alternate-current 1.4.0
- animatica 0.5+1.19
- appleskin 2.4.1+mc1.19
- architectury 6.4.62
- armorstatues 4.0.4
- autoclicker-fabric 1.19.2-1.4.2-build.19
- backportgamerules 1.0.1+1.19.2
- badpackets 0.2.1
- balm-fabric 4.5.2+0
- barteringstation 4.0.3
- bedrockminer 1.19.2
- betterbiomeblend 1.19-1.3.6-fabric
- bettermounthud 1.2.0
- bettertridents 4.0.2
- blanket-client-tweaks 1.1.2
- blue_endless_jankson 1.2.1 via owo
- bookshelf 16.2.17
- borderlessmining 1.1.5+1.19
- caffeineconfig 1.0.0+1.17 via sodium-extra
- cardinal-components-base 5.0.2 via puzzleslib
- cardinal-components-block 5.0.2 via puzzleslib
- cardinal-components-chunk 5.0.2 via puzzleslib
- cardinal-components-entity 5.0.2 via puzzleslib
- cardinal-components-item 5.0.1 via polymorph
- cardinal-components-world 5.0.2 via puzzleslib
- carpet 1.4.84
- carpet-fixes 1.19-1.12.2
- cem 0.7.1_S7_1.19
- charm 4.4.4
- charmofundying 6.0.0+1.19.2
- chunk_destroyer_fabric 1.2.0
- citresewn 1.1.2+1.19.2
- citresewn-defaults 1.1.2+1.19.2 via citresewn
- clickadv 3.0
- cloth-api 4.0.65
- cloth-basic-math 0.6.1 via cloth-api
- cloth-client-events-v0 4.0.65 via cloth-api
- cloth-common-events-v1 4.0.65 via cloth-api
- cloth-config 8.2.88
- cloth-scissors-api-v1 4.0.65 via cloth-api
- cloth-utils-v1 4.0.65 via cloth-api
- coat 1.0.0-beta.19+mc22w17a via completeconfig
- colormatic 3.1.2+mc.1.19
- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
- com_eliotlash_mclib_mclib 20 via geckolib3
- com_github_llamalad7_mixinextras 0.1.1 via luggage
- com_google_guava_guava 31.1-jre via fabrizoom
- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
- com_moandjiezana_toml_toml4j 0.7.2 via charm
- com_typesafe_config 1.4.2 via fabrizoom
- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
- completeconfig 2.1.0
- completeconfig-base 2.1.0 via completeconfig
- completeconfig-gui-cloth 2.1.0 via completeconfig
- completeconfig-gui-coat 2.1.0 via completeconfig
- completeconfig-gui-yacl 2.1.0 via completeconfig
- compressed 1.8.0
- conditional-mixin 0.3.1 via carpet-fixes
- config2brigadier 1.2.1 via simplevillagers
- configuration 2.1.0
- continuity 2.0.1+1.19
- crowdin-translate 1.4+1.19 via stepup
- cull-less-leaves 1.0.6
- debugify 2.8.0
- disable_custom_worlds_advice 3.0
- display_case 1.0.3
- dynamicfps 2.2.0
- easiervillagertrading 1.19.1-fabric0.58.5-1.5.4
- elytraslot 6.1.0+1.19.2
- enhancedblockentities 0.7.2+1.19.2
- entity_texture_features 4.3.0
- entityculling 1.5.2-mc1.19
- error_notifier 1.0.9 via roughlyenoughitems
- exordium 1.0.1-mc1.19.2
- fabric-api 0.73.2+1.19.2
- fabric-api-base 0.4.15+8f4e8eb390 via fabric-api
- fabric-api-lookup-api-v1 1.6.14+93d8cb8290 via fabric-api
- fabric-biome-api-v1 9.1.0+82db024a90 via fabric-api
- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
- fabric-blockrenderlayer-v1 1.1.24+c6af733c90 via fabric-api
- fabric-client-tags-api-v1 1.0.5+b35fea8390 via fabric-api
- fabric-command-api-v1 1.2.16+f71b366f90 via fabric-api
- fabric-command-api-v2 2.2.1+413cbbc790 via fabric-api
- fabric-commands-v0 0.2.33+df3654b390 via fabric-api
- fabric-containers-v0 0.1.41+df3654b390 via fabric-api
- fabric-content-registries-v0 3.5.1+7c6cd14d90 via fabric-api
- fabric-convention-tags-v1 1.2.2+27265b3490 via fabric-api
- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
- fabric-data-generation-api-v1 5.3.7+413cbbc790 via fabric-api
- fabric-dimensions-v1 2.1.35+0d0f210290 via fabric-api
- fabric-entity-events-v1 1.5.4+9244241690 via fabric-api
- fabric-events-interaction-v0 0.4.34+562bff6e90 via fabric-api
- fabric-events-lifecycle-v0 0.2.35+df3654b390 via fabric-api
- fabric-furnaces 2.2.0-1.19.2
- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
- fabric-item-api-v1 1.6.5+dce4603e90 via fabric-api
- fabric-item-groups-v0 0.3.38+9244241690 via fabric-api
- fabric-key-binding-api-v1 1.0.25+5c4fce2890 via fabric-api
- fabric-keybindings-v0 0.2.23+df3654b390 via fabric-api
- fabric-language-kotlin 1.9.1+kotlin.1.8.10
- fabric-lifecycle-events-v1 2.2.4+1b46dc7890 via fabric-api
- fabric-loot-api-v2 1.1.12+83a8659290 via fabric-api
- fabric-loot-tables-v1 1.1.15+9e7660c690 via fabric-api
- fabric-message-api-v1 5.0.7+93d8cb8290 via fabric-api
- fabric-mining-level-api-v1 2.1.23+33fbc73890 via fabric-api
- fabric-models-v0 0.3.21+c6af733c90 via fabric-api
- fabric-networking-api-v1 1.2.11+10eb22f490 via fabric-api
- fabric-networking-v0 0.3.28+df3654b390 via fabric-api
- fabric-object-builder-api-v1 4.2.1+d8ef690890 via fabric-api
- fabric-particles-v1 1.0.14+4d0d570390 via fabric-api
- fabric-permissions-api-v0 0.1-SNAPSHOT via simplevillagers
- fabric-recipe-api-v1 1.0.1+413cbbc790 via fabric-api
- fabric-registry-sync-v0 0.9.32+9244241690 via fabric-api
- fabric-renderer-api-v1 1.2.1+2e5408b590 via fabric-api
- fabric-renderer-indigo 0.7.1+2e5408b590 via fabric-api
- fabric-renderer-registries-v1 3.2.24+df3654b390 via fabric-api
- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690 via fabric-api
- fabric-rendering-fluids-v1 3.0.11+4d0d570390 via fabric-api
- fabric-rendering-v0 1.1.27+df3654b390 via fabric-api
- fabric-rendering-v1 1.12.1+d8ef690890 via fabric-api
- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
- fabric-resource-loader-v0 0.8.3+251d254a90 via fabric-api
- fabric-screen-api-v1 1.0.32+4d0d570390 via fabric-api
- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90 via fabric-api
- fabric-sound-api-v1 1.0.2+c4f28df590 via fabric-api
- fabric-textures-v0 1.0.24+aeb40ebe90 via fabric-api
- fabric-transfer-api-v1 2.1.6+413cbbc790 via fabric-api
- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
- fabricloader 0.14.15
- fabricskyboxes 0.6.1+mc1.19.2
- fabrishot 1.9.1
- fabrizoom 1.2.1
- fastchest 1.3+1.19
- faster_entity_animations 1.5.7
- fastload 2.6.10
- ferritecore 5.0.3
- fixmyspawnr 1.1.3
- flytre_lib 1.8.8
- forge_tags 3.0 via luggage
- forgeconfigapiport 4.2.11
- fsb-interop 1.1.3+mc1.19.2-build.25
- gbfabrictools 1.3.4+1.19 via easiervillagertrading
- geckolib3 3.1.38
- globedimension 1.19.2-1.4.0
- gobber2 2.6.61
- gravelminer 13.0.0
- holdthatchunk 2.0.1
- hplus 3.3.3
- indium 1.0.9+mc1.19.2
- infinitevillagertrading 1.19.1-fabric0.58.5-1.1
- inmis 2.7.1-1.19
- invisibilitycloak 2.1.0
- io_github_douira_glsl-transformer 2.0.0-pre8 via iris
- io_leangen_geantyref_geantyref 1.3.12 via fabrizoom
- iris 1.5.0
- isxander-main-menu-credits 1.1.1
- itemmodelfix 1.0.3+1.19
- java 17
- jumpoverfences 1.1.0
- kibe 1.9.10-BETA+1.19
- krypton 0.2.1
- kyrptconfig 1.4.16-1.19 via quickshulker
- lambdabettergrass 1.3.0+1.19
- lambdynlights 2.2.0+1.19.2
- languagereload 1.4.1
- lazydfu 0.1.3
- leavemybarsalone 4.0.0
- litematica 0.12.6
- lithium 0.10.4
- luggage 1.19-1.5.2
- malilib 0.13.0
- malusphaethusa 1.1.2
- mcwroofs 2.2.2
- megane 8.3.0
- megane-alloy-forgery 8.3.0 via megane
- megane-api 8.3.0 via megane
- megane-fabric-transfer 8.3.0 via megane
- megane-kibe 8.3.0 via megane
- megane-luggage 8.3.0 via megane
- megane-runtime 8.3.0 via megane
- megane-vanilla 8.3.0 via megane
- memoryleakfix 1.19.1-0.7.0
- merenc 1.10
- midnightcontrols 1.7.1+1.19
- midnightlib 0.6.1 via midnightcontrols
- minecraft 1.19.2
- mixin-conflict-helper 1.2.0
- mixintrace 1.1.1+1.17
- modmenu 4.1.2
- more_slabs_stairs_and_walls 2.2.0
- morechathistory 1.1.1
- moreculling 1.19.1-0.12.4
- morepotions 1.0.3
- nochatreports 1.19.2-v1.13.12
- noenchantcap 2.2.4
- nofade 1.18-2.0.1
- omega-config 1.2.3-1.18.1 via fabric-furnaces
- optigui 1.1.6
- org_anarres_jcpp 1.4.14 via iris
- org_antlr_antlr4-runtime 4.11.1 via iris
- org_apache_commons_commons-text 1.9 via optigui
- org_apache_httpcomponents_httpmime 4.5.10 via entity_texture_features
- org_aperlambda_lambdajcommon 1.8.1 via midnightcontrols
- org_jetbrains_kotlin_kotlin-reflect 1.8.10 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 1.8.10 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.10 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.10 via fabric-language-kotlin
- org_jetbrains_kotlinx_atomicfu-jvm 0.19.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
- org_joml_joml 1.10.4 via sodium
- org_spongepowered_configurate-core 4.1.2 via fabrizoom
- org_spongepowered_configurate-extra-kotlin 4.1.2 via fabrizoom
- org_spongepowered_configurate-hocon 4.1.2 via fabrizoom
- owo 0.8.5+1.19
- packet_tweaker 0.3.0+1.18.2 via polymer
- pickupnotifier 4.2.4
- playerabilitylib 1.6.0 via kibe
- polymer 0.2.24+1.19.2 via polymer-all
- polymer-all 0.2.24+1.19.2
- polymer-blocks-ext 0.1.0-alpha.9+1.19.2 via polymer-all
- polymer-registry-sync-manipulator 0.0.3+1.19.2 via polymer
- polymorph 0.46.1+1.19.2
- portablemobfarm 1.0.1
- pride 1.1.2+1.19 via lambdynlights
- pugh_lib 1.4.15 via gobber2
- pugh_tools 1.3.23 via gobber2
- puzzle 1.4.0-1.19
- puzzle-base 1.4.0-1.19 via puzzle
- puzzle-gui 1.4.0-1.19 via puzzle
- puzzle-models 1.4.0-1.19 via puzzle
- puzzle-splashscreen 1.4.0-1.19 via puzzle
- puzzleslib 4.3.12
- quickshulker 1.3.9-1.19
- raised 1.2.1
- reeses-sodium-options 1.4.9+mc1.19.2-build.67
- reinfcore 3.0.3+1.19 via reinfshulker
- reinfshulker 2.2.0+1.19
- ringsofascension 1.0
- roughlyenoughitems 9.1.587
- roughlyenoughresources 2.6.0
- server_translations_api 1.4.16+1.19 via simplevillagers
- sgui 1.1.3+1.19.1 via simplevillagers
- shulkerboxtooltip 3.2.2+1.19.2
- shulkerutils 1.0.4-1.19 via quickshulker
- simplevillagers 1.4.1
- smoothboot 1.19-1.7.1
- smoothchunk 1.19.1-2.0
- smoothscrollingeverywhere 3.0.3-unstable
- sodium 0.4.4+build.18
- sodium-extra 0.4.16+mc1.19.2-build.90
- spawnermod 1.2.0
- spectrelib 0.11.0+1.19 via polymorph
- spikyspikes 4.0.7
- spruceui 4.1.0+1.19.2 via lambdynlights
- stacc 1.3.4 via stacker
- stacker 3.0.2-1.19.x
- starbidous_more_end_cities 1.0.0
- starlight 1.1.1+fabric.ae22326
- stepup 1.19.1-fabric0.58.5-1.1
- stylisheffects 4.3.2
- taxfreelevels 1.3.3
- tlskincape 1.27
- trinkets 3.4.2
- vanillatweaks 1.5.63
- worldedit 7.2.12+6240-87f4ae1
- worldeditcui 1.19.2+01
- wthit 5.13.4
- wurst v7.30-MC1.19.2
- xaerominimap 23.1.0
- xaeroworldmap 1.28.9
- yet-another-config-lib 1.7.1
- yosbr 0.1.1
```

## Game info
Minecraft Version: 1.19.2
Fabric Loader Version: 0.14.15

##Additional Notes
I opened an issue a few months ago (#406) and the answer I got is to add the line "mixin.entity.hopper_minecart=false
to the lithium.properties file in the config folder" but after upgrading to 1.19.2 this workaround seemed to stop working. I hope someone can help me with this because the author of this mod is kinda inactive and never check the opened issues in his repo. Also, [he has his own repo](https://github.com/Flytre/hplus2), not "Hopper+ is not open source"

**Comment by 2No2Name** [comment]
Are you sure this crash report was created with lithium's config `mixin.entity.hopper_minecart=false`?

**Comment by bvhfve** [comment]
When I first saw the crash report I thought I messed something up but I re-checked a few times to make sure and even with the exact lithium config my game still crashed

**Comment by 2No2Name** [comment]
Can you post the log and the new crash report that was generated

**Comment by 2No2Name** [comment]
I suggest to also add `mixin.block.hopper=false`

**Comment by 2No2Name** [comment]
https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json
