### ISSUE TITLE
getChunkOffThread error when loading chunks?

### ISSUE THREAD

**Issue by ereese99** [jellysquid3/Lithium#456]
-- Head --
Thread: Server Watchdog
Stacktrace:
	at java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.6/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at net.minecraft.class_1255.method_20813(class_1255.java:152)
	at net.minecraft.class_1255.method_18857(class_1255.java:142)
	at net.minecraft.class_3215.getChunkBlocking(class_3215.java:1781)
	at net.minecraft.class_3215.method_12121(class_3215.java:1677)
	at net.minecraft.class_3215.mdb2c32d$lithium$lambda$getChunkOffThread$0$0(class_3215.java:1689)
	at net.minecraft.class_3215$$Lambda$26685/0x0000000803ec5dc8.get(Unknown Source)
	at java.base@17.0.6/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:557)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:566)
	at net.minecraft.class_3215.method_19492(class_3215.java:279)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)

**Comment by itsdinkd** [comment]
same.


```java
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2023-03-13 20:26:12
Description: Watching Server

java.lang.Error: Watchdog
	at jdk.internal.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at net.minecraft.util.thread.ThreadExecutor.waitForTasks(ThreadExecutor.java:152)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:142)
	at net.minecraft.server.world.ServerChunkManager.getChunkBlocking(ServerChunkManager.java:205)
	at net.minecraft.server.world.ServerChunkManager.getChunk(ServerChunkManager.java:101)
	at net.minecraft.server.world.ServerChunkManager.md3c0a1f$lambda$getChunkOffThread$0$0(ServerChunkManager.java:113)
	at net.minecraft.class_3215$$Lambda$33950/0x00000008050d66c8.get(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:157)
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.executeTask(ServerChunkManager.java:557)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:131)
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.runTask(ServerChunkManager.java:566)
	at net.minecraft.server.world.ServerChunkManager.executeQueuedTasks(ServerChunkManager.java:279)
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:752)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:140)
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.handler$ckh000$modifiedRunLoop(MinecraftServer.java:146)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$29538/0x000000080489dc50.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:833)
	```

**Comment by 2No2Name** [comment]
Neither of those indicate that lithium has anything to do with the issue.
