### ISSUE TITLE
Receiver class net.minecraft.class_2614 does not define or inherit an implementation of the resolved method 'boolean canReceiveTransferCooldown()' of interface me.jellysquid.mods.lithium.api.inventory.LithiumCooldownReceivingInventory

### ISSUE THREAD

**Issue by lospejos** [jellysquid3/Lithium#476]
### Version

`lithium-fabric-mc1.20-0.11.2`

### Reproduction Steps

Unfortunately I cannot set the exact steps to reproduce, because a while game was running ok. But at some point while playing a game unexpected crash occurred.

Disclaimer: I'm not sure is this crash caused by a Lithium mod or some other mod (e.g. mods compatibility issue).
Since `lithium` was mentioned in stack trace, I supposed that this mod causes crash. If it is not true, sorry for this issue.
Stack trace is
```
[02:08:14] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking block entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.AbstractMethodError: Receiver class net.minecraft.class_2614 does not define or inherit an implementation of the resolved method 'boolean canReceiveTransferCooldown()' of interface me.jellysquid.mods.lithium.api.inventory.LithiumCooldownReceivingInventory.
	at net.minecraft.class_2614.handler$eld000$lithium$lithiumInsert(class_2614.java:679) ~[client-intermediary.jar:?]
	at net.minecraft.class_2614.method_11246(class_2614.java:148) ~[client-intermediary.jar:?]
	at net.minecraft.class_2614.method_11243(class_2614.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_2614.method_31692(class_2614.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:470) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:390) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[client-intermediary.jar:?]
	... 5 more
```
Warning: my build contains plenty of mods, and the full log contains many errors and warnings from other mods. I don't know are they related to this crash or not.

### Crash Report File

The archive contains log file, crash report file and mods list file:
[minecraft_crash_2023-06-11.zip](https://github.com/CaffeineMC/lithium-fabric/files/11713506/minecraft_crash_2023-06-11.zip)

### Minecraft Save

No applicable saves.

### Additional Information

When I removed Lithium mod (preserving all the rest mods), this crash not appeared on that situation where earlier crash with lithium mod occurred.

**Comment by 2No2Name** [comment]
Fixed on their side
