### ISSUE TITLE
Lithium on FreeBSD has issuues with missing files which are present on Linux. 

### ISSUE THREAD

**Issue by CatPasswd** [jellysquid3/Lithium#600]
#### Instructions

This is a template for the issue you are about to open! It will help you provide the information necessary
to complete your **bug report**. Before you open an issue, ensure you've completed every step on the checklist below.

- Have you used the search tool to find similar issues? Make sure you are not opening a duplicate.
- Are you using the latest version of the mod? If not, try updating to see if it resolves your issue.

All good? Please read through the sections below, and fill out any lines starting with an arrow. Then, remove
everything above this dashed line (including the line itself.)

------------------------

### Version Information

lithium-fabric-0.14.3+mc1.21.3.jar

### Expected Behavior

Eliminations of the error,

### Actual Behavior
[02:47:52] [main/INFO]: Loaded configuration file for Lithium: 140 options available, 1 override(s) found
[02:47:53] [main/WARN]: Error loading class: vazkii/botania/common/entity/EntityManaBurst (java.lang.ClassNotFoundException: vazkii/botania/common/entity/EntityManaBurst)
[02:47:53] [main/WARN]: Error loading class: vazkii/botania/common/item/ItemLaputaShard (java.lang.ClassNotFoundException: vazkii/botania/common/item/ItemLaputaShard)
[02:47:53] [main/WARN]: @Mixin target vazkii.botania.common.item.ItemLaputaShard was not found goml.mixins.json:compat.BotaniaItemLaputaShardMixin from mod goml
[02:47:53] [main/WARN]: Error loading class: org/dynmap/Client (java.lang.ClassNotFoundException: org/dynmap/Client)
[02:47:54] [main/INFO]: Force-enabling mixin 'compat.transfer_api.TransferApiHelperMixin' as rule 'mixin.compat.transfer_api' (added by mods [lithium]) enables it
[02:47:55] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[02:47:57] [main/WARN]: File not found or not readable: /var/run/dmesg.boot
[02:47:57] [main/WARN]: File not found or not readable: /var/run/dmesg.boot
[02:47:57] [main/WARN]: Failed retrieving storage space for workdir
java.io.IOException: Mount point not found in fstab
	at java.base/sun.nio.fs.BsdFileStore.findMountEntry(BsdFileStore.java:88) ~[?:?]
	at java.base/sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:69) ~[?:?]
	at java.base/sun.nio.fs.BsdFileStore.<init>(BsdFileStore.java:42) ~[?:?]
	at java.base/sun.nio.fs.BsdFileSystemProvider.getFileStore(BsdFileSystemProvider.java:48) ~[?:?]
	at java.base/sun.nio.fs.BsdFileSystemProvider.getFileStore(BsdFileSystemProvider.java:36) ~[?:?]
	at java.base/sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:422) ~[?:?]
	at java.base/java.nio.file.Files.getFileStore(Files.java:1496) ~[?:?]
	at knot/net.minecraft.class_6396.method_59899(class_6396.java:167) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_6396.method_59897(class_6396.java:150) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_6396.method_37121(class_6396.java:87) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_6396.method_37128(class_6396.java:82) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_6396.method_37143(class_6396.java:56) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_6396.method_37121(class_6396.java:87) [server-intermediary.jar:?]
	at knot/net.minecraft.class_6396.<init>(class_6396.java:56) [server-intermediary.jar:?]
	at knot/net.minecraft.class_128.<init>(class_128.java:35) [server-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_24305(class_128.java:234) [server-intermediary.jar:?]
	at knot/net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.3-loader.0.16.9-launcher.1.0.1.jar:1.0.1

### Reproduction Steps
Use the Lithium mod on a Fabric 1.21.3 server with freebsd.

### Other Information
minecraft@nixcraft:~/mods $ ls -a
.                                               blossom-homes-2.2.6+1.21.3.jar                  geyser-fabric-Geyser-Fabric-2.5.1-b724.jar
..                                              blossom-lib-2.5.10+1.21.3.jar                   goml-1.14.1+1.21.3.jar
Discord-MC-Chat-2.3.5.jar                       blossom-tpa-2.2.6+1.21.3.jar                    inventoryessentials-fabric-1.21.3-21.3.2.jar
LuckPerms-Fabric-5.4.145.jar                    bluemap-5.5-fabric.jar                          lithium-fabric-0.14.3+mc1.21.3.jar
MinecraftStatsCLI.jar                           fabric-api-0.110.0+1.21.3.jar                   luckperms
NoChatReports-FABRIC-1.21.3-v2.10.1.jar         fabric-carpet-1.21.2-1.4.158+v241022.jar        polymer-bundled-0.10.2+1.21.3.jar
ViaFabric-0.4.16+85-main.jar                    fabric-language-kotlin-1.13.0+kotlin.2.1.0.jar  sessility-fabric-mod-0.6.4.jar
balm-fabric-1.21.3-21.3.3.jar                   fabric-permissions-api-0.3.3.jar                sodium-fabric-0.6.1+mc1.21.3.jar
blossom-back-2.1.6+1.21.3.jar                   fabric-spawn-1.0.1+1.21.3.jar                   spark-1.10.115-fabric.jar
minecraft@nixcraft:~/mods $

**Comment by jellysquid3** [comment]
The log file is misleading, since when the game goes to create a crash report, it ends up crashing a second time. So the error messages you're seeing are actually from Minecraft not being able to include information in the crash report about the kernel log and remaining hard drive space.

Unfortunately, that means the *actual* crash reason is not present. So it is impossible to know what is going wrong here unless you can attach a debugger and catch the exception before the crash report gets created.

**Comment by 2No2Name** [comment]
One user on discord claims this is an oshi issue https://host.ithundxr.dev/RFzilE.png
