### ISSUE TITLE
Server hangs under certain conditions when players go through a Nether portal

### ISSUE THREAD

**Issue by Surader** [jellysquid3/Lithium#87]
### Reproduction Steps
We have had 3 people join our server and ever since updating to 1.16.1 it is random but to those 3 it crashes whenever they enter or leave the nether, now it is not 100% of the time for them but random
1. Affected Player goes into nether Portal
2. Server instantly crashed

### Crash Report File
[crash-2020-07-21_16.43.16-server.txt](https://github.com/jellysquid3/lithium-fabric/files/4957604/crash-2020-07-21_16.43.16-server.txt)

### Additional Information
Any help would be appreciated and when I say instant crash it is within 3 seconds of them going through the portal and server stops, I am not the greatest at reading crash reports so any help would be appreciated.

**Comment by 2No2Name** [comment]
Looking at the crashreport reveals that the server thread is waiting for a chunk to load, and another thread is working on light updates.

"Worker-Main-62" Id=317 RUNNABLE
	at net.minecraft.class_3554.method_15492(class_3554.java:212)
	at net.minecraft.class_3558.method_15516(class_3558.java:193)    (this is ChunkLightProvider.doLightUpdates)
	at net.minecraft.class_3568.method_15563(class_3568.java:61)
	at net.minecraft.class_3227.method_14277(class_3227.java:176)
	at net.minecraft.class_3227.method_19505(class_3227.java:155)
	at net.minecraft.class_3227$$Lambda$4680/317034848.run(Unknown Source)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	...

So this is probably a similar issue as in #37 that there are just too many things to do in one tick. (probably a lot of light updates, or it was just working on light updates when the watchdog got the stacktraces). In your server log there should be a line stating "A single server tick took ...", so it did not crash immediately, but decided to shut down the server after 60 (default) seconds of waiting for the tick to finish.

Is there any kind of machine running in your world that causes a lot of light updates to happen?

**Comment by Surader** [comment]
We are playing amplified survival could that be the reason it could have lighting update issues?

**Comment by Surader** [comment]
I disabled watchdog and so far it hasn't crashed

**Comment by Surader** [comment]
Not that I'm aware we have a ton of campfires for our nether tunnels but its 400 per 800 block sections, a few piglin farms, and that's it

**Comment by mdedmon** [comment]
I'm having a similar issue. It's not crashing my server, but the character "sounds" like he appears on the nether side, but the display never refreshes and you're stuck and can't move. If you disconnect / reconnect, you are in the nether, where you should be.  The nether portals are on the top of the nether ceiling in my server. They all seem to behave this way. Also, if I leave the nether to go to a portal that is at a typical height in the overworld, it exhibits the same behavior.

**Comment by jellysquid3** [comment]
@mdedmon Please make sure you are using the latest version of Lithium (version 0.5.4 as of the time of writing.) Your issue sounds like a chunk loading problem on dimension change that was recently fixed.

**Comment by mdedmon** [comment]
Thanks - Will do, I'm running 0.5.3 right now. I installed it yesterday.

**Comment by mdedmon** [comment]
Thanks again - that fixed it.

**Comment by LucilleTea** [comment]
I was experiencing this issue on my server (portal based, not machinery based as in issue 37). It has completely disappeared since I updated to Phosphor's dev branch with the recent commits from PhiPro.
I was previously experiencing the issue running on 1.16.1 with either stable phosphor, or dev phosphor as of commit 50f6d6b167fdd5f78eb5752f94fd5f65b8a8a91e
It's now gone running on 1.16.3 with phosphor commit 685f1fa60800bbbbe4784ed1906c5f66e130c584

I never managed to reproduce this in a testing environment, only my live server, so I'm a bit hesitant to experiment with it much more to narrow down the exact fix. It's true that I'm also running a newer lithium version here in 1.16.3, but I don't know of any changes made to address this in lithium.

**Comment by MatthewClair** [comment]
I seem to be having this issue occasionally on my server.  I'm using the latest Phosphor (0.71+build.11) and Lithium (0.6.4) releases.  Possibly interesting, I am also running an amplified world.  I've attached a crash report.  Let me know if there is any other info/logging that could be helpful.

[crash-2021-03-19_15.05.26-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/6191484/crash-2021-03-19_15.05.26-server.txt)

**Comment by James103** [comment]
For anyone still having this issue, can you please retry with the [Starlight](https://github.com/PaperMC/Starlight) mod instead of Phosphor?
